// 人教版英语单词数据
const wordData = {
  grade1: {
    semester1: [
      { en: 'apple', cn: '苹果' },
      { en: 'book', cn: '书' },
      { en: 'cat', cn: '猫' },
      { en: 'dog', cn: '狗' },
      { en: 'egg', cn: '蛋' }
    ],
    semester2: [
      { en: 'fish', cn: '鱼' },
      { en: 'girl', cn: '女孩' },
      { en: 'hat', cn: '帽子' },
      { en: 'ice', cn: '冰' },
      { en: 'jump', cn: '跳' }
    ]
  },
  grade2: {
    semester1: [
      { en: 'ball', cn: '球' },
      { en: 'cake', cn: '蛋糕' },
      { en: 'desk', cn: '桌子' },
      { en: 'eye', cn: '眼睛' },
      { en: 'face', cn: '脸' }
    ],
    semester2: [
      { en: 'game', cn: '游戏' },
      { en: 'hand', cn: '手' },
      { en: 'ink', cn: '墨水' },
      { en: 'juice', cn: '果汁' },
      { en: 'king', cn: '国王' }
    ]
  },
  grade3: {
    semester1: [
      { en: 'bread', cn: '面包' },
      { en: 'chair', cn: '椅子' },
      { en: 'door', cn: '门' },
      { en: 'earth', cn: '地球' },
      { en: 'flower', cn: '花' }
    ],
    semester2: [
      { en: 'grass', cn: '草' },
      { en: 'house', cn: '房子' },
      { en: 'island', cn: '岛屿' },
      { en: 'jacket', cn: '夹克' },
      { en: 'kitchen', cn: '厨房' }
    ]
  },
  grade4: {
    semester1: [
      { en: 'animal', cn: '动物' },
      { en: 'brother', cn: '兄弟' },
      { en: 'computer', cn: '电脑' },
      { en: 'doctor', cn: '医生' },
      { en: 'elephant', cn: '大象' }
    ],
    semester2: [
      { en: 'family', cn: '家庭' },
      { en: 'garden', cn: '花园' },
      { en: 'hospital', cn: '医院' },
      { en: 'internet', cn: '互联网' },
      { en: 'journey', cn: '旅程' }
    ]
  },
  grade5: {
    semester1: [
      { en: 'beautiful', cn: '美丽的' },
      { en: 'careful', cn: '小心的' },
      { en: 'dangerous', cn: '危险的' },
      { en: 'excellent', cn: '优秀的' },
      { en: 'friendly', cn: '友好的' }
    ],
    semester2: [
      { en: 'generous', cn: '慷慨的' },
      { en: 'healthy', cn: '健康的' },
      { en: 'important', cn: '重要的' },
      { en: 'jealous', cn: '嫉妒的' },
      { en: 'kind', cn: '善良的' }
    ]
  },
  grade6: {
    semester1: [
      { en: 'science', cn: '科学' },
      { en: 'museum', cn: '博物馆' },
      { en: 'post office', cn: '邮局' },
      { en: 'bookstore', cn: '书店' },
      { en: 'cinema', cn: '电影院' },
      { en: 'hospital', cn: '医院' },
      { en: 'crossing', cn: '十字路口' },
      { en: 'turn', cn: '转弯' },
      { en: 'left', cn: '左' },
      { en: 'straight', cn: '笔直地' },
      { en: 'right', cn: '右' },
      { en: 'ask', cn: '问' },
      { en: 'sir', cn: '先生' },
      { en: 'interesting', cn: '有趣的' },
      { en: 'Italian', cn: '意大利的' },
      { en: 'restaurant', cn: '餐馆' },
      { en: 'pizza', cn: '比萨饼' },
      { en: 'street', cn: '大街；街道' },
      { en: 'get', cn: '到达' },
      { en: 'GPS', cn: '全球（卫星）定位系统' },
      { en: 'gave', cn: '给供；交给' },
      { en: 'feature', cn: '特点' },
      { en: 'follow', cn: '跟着' },
      { en: 'far', cn: '较远的' },
      { en: 'tell', cn: '告诉' },
      { en: 'on foot', cn: '步行' },
      { en: 'by', cn: '乘（表示方式）' },
      { en: 'bus', cn: '公共汽车' },
      { en: 'plane', cn: '飞机' },
      { en: 'taxi', cn: '出租汽车' },
      { en: 'ship', cn: '（大）船' },
      { en: 'subway', cn: '地铁' },
      { en: 'train', cn: '火车' },
      { en: 'slow', cn: '慢的' },
      { en: 'down', cn: '减少；降低' },
      { en: 'slow down', cn: '慢下来' },
      { en: 'stop', cn: '停下' },
      { en: 'Mrs', cn: '夫人' },
      { en: 'early', cn: '早到的' },
      { en: 'helmet', cn: '头盔' },
      { en: 'must', cn: '必须' },
      { en: 'wear', cn: '戴' },
      { en: 'attention', cn: '注意' },
      { en: 'pay attention to', cn: '注意' },
      { en: 'traffic', cn: '交通' },
      { en: 'traffic lights', cn: '交通信号灯' }
    ],
    semester2: [
      { en: 'freedom', cn: '自由' },
      { en: 'government', cn: '政府' },
      { en: 'history', cn: '历史' },
      { en: 'information', cn: '信息' },
      { en: 'knowledge', cn: '知识' }
    ]
  },
  grade7: {
    semester1: [
      { en: 'advice', cn: '建议' },
      { en: 'agree', cn: '同意' },
      { en: 'angry', cn: '生气的' },
      { en: 'arrive', cn: '到达' },
      { en: 'autumn', cn: '秋天' },
      { en: 'believe', cn: '相信' },
      { en: 'belong', cn: '属于' },
      { en: 'bridge', cn: '桥' },
      { en: 'cheap', cn: '便宜的' },
      { en: 'choose', cn: '选择' },
      { en: 'clean', cn: '清洁的' },
      { en: 'clear', cn: '清晰的' },
      { en: 'clever', cn: '聪明的' },
      { en: 'collect', cn: '收集' },
      { en: 'comfortable', cn: '舒适的' },
      { en: 'communicate', cn: '交流' },
      { en: 'compare', cn: '比较' },
      { en: 'competition', cn: '比赛' },
      { en: 'complete', cn: '完成' },
      { en: 'continue', cn: '继续' },
      { en: 'conversation', cn: '对话' },
      { en: 'correct', cn: '正确的' },
      { en: 'country', cn: '国家' },
      { en: 'courage', cn: '勇气' },
      { en: 'cousin', cn: '堂兄弟/姐妹' },
      { en: 'culture', cn: '文化' },
      { en: 'dangerous', cn: '危险的' },
      { en: 'decide', cn: '决定' },
      { en: 'delicious', cn: '美味的' },
      { en: 'describe', cn: '描述' },
      { en: 'dictionary', cn: '字典' },
      { en: 'difficult', cn: '困难的' },
      { en: 'dinner', cn: '晚餐' },
      { en: 'direction', cn: '方向' },
      { en: 'discover', cn: '发现' },
      { en: 'discuss', cn: '讨论' },
      { en: 'distance', cn: '距离' },
      { en: 'dream', cn: '梦想' },
      { en: 'during', cn: '在...期间' },
      { en: 'education', cn: '教育' },
      { en: 'either', cn: '两者之一' },
      { en: 'enjoy', cn: '享受' },
      { en: 'enough', cn: '足够的' },
      { en: 'environment', cn: '环境' },
      { en: 'especially', cn: '特别地' },
      { en: 'evening', cn: '傍晚' },
      { en: 'everyone', cn: '每个人' },
      { en: 'everything', cn: '每件事' },
      { en: 'everywhere', cn: '到处' },
      { en: 'example', cn: '例子' },
      { en: 'excited', cn: '兴奋的' },
      { en: 'exercise', cn: '锻炼' },
      { en: 'experience', cn: '经验' },
      { en: 'explain', cn: '解释' },
      { en: 'famous', cn: '著名的' },
      { en: 'favorite', cn: '最喜欢的' },
      { en: 'feeling', cn: '感觉' },
      { en: 'finally', cn: '最后' },
      { en: 'follow', cn: '跟随' },
      { en: 'foreign', cn: '外国的' },
      { en: 'forest', cn: '森林' },
      { en: 'forget', cn: '忘记' },
      { en: 'friendly', cn: '友好的' },
      { en: 'future', cn: '未来' },
      { en: 'general', cn: '一般的' },
      { en: 'happen', cn: '发生' },
      { en: 'healthy', cn: '健康的' },
      { en: 'helpful', cn: '有帮助的' },
      { en: 'history', cn: '历史' },
      { en: 'holiday', cn: '假期' },
      { en: 'however', cn: '然而' },
      { en: 'imagine', cn: '想象' },
      { en: 'important', cn: '重要的' },
      { en: 'improve', cn: '提高' },
      { en: 'include', cn: '包括' },
      { en: 'information', cn: '信息' },
      { en: 'interest', cn: '兴趣' },
      { en: 'introduce', cn: '介绍' },
      { en: 'invite', cn: '邀请' },
      { en: 'journey', cn: '旅程' },
      { en: 'language', cn: '语言' },
      { en: 'learn', cn: '学习' },
      { en: 'library', cn: '图书馆' },
      { en: 'listen', cn: '听' },
      { en: 'machine', cn: '机器' },
      { en: 'magazine', cn: '杂志' },
      { en: 'material', cn: '材料' },
      { en: 'meaning', cn: '意义' },
      { en: 'measure', cn: '测量' },
      { en: 'medicine', cn: '药物' },
      { en: 'message', cn: '消息' },
      { en: 'minute', cn: '分钟' },
      { en: 'mistake', cn: '错误' },
      { en: 'modern', cn: '现代的' },
      { en: 'mountain', cn: '山' },
      { en: 'natural', cn: '自然的' },
      { en: 'necessary', cn: '必要的' },
      { en: 'neighbor', cn: '邻居' },
      { en: 'neither', cn: '两者都不' },
      { en: 'nervous', cn: '紧张的' },
      { en: 'normal', cn: '正常的' },
      { en: 'notice', cn: '注意' },
      { en: 'number', cn: '数字' },
      { en: 'opinion', cn: '意见' },
      { en: 'opposite', cn: '相反的' },
      { en: 'ordinary', cn: '普通的' },
      { en: 'organize', cn: '组织' },
      { en: 'original', cn: '原始的' },
      { en: 'ourselves', cn: ' ourselves' },
      { en: 'outside', cn: '外面' },
      { en: 'perhaps', cn: '也许' },
      { en: 'personal', cn: '个人的' },
      { en: 'physical', cn: '身体的' },
      { en: 'picture', cn: '图片' },
      { en: 'pleasant', cn: '愉快的' },
      { en: 'popular', cn: '流行的' },
      { en: 'position', cn: '位置' },
      { en: 'possible', cn: '可能的' },
      { en: 'practice', cn: '练习' },
      { en: 'prepare', cn: '准备' },
      { en: 'present', cn: '礼物' },
      { en: 'problem', cn: '问题' },
      { en: 'produce', cn: '生产' },
      { en: 'promise', cn: '承诺' },
      { en: 'protect', cn: '保护' },
      { en: 'provide', cn: '提供' },
      { en: 'purpose', cn: '目的' },
      { en: 'quality', cn: '质量' },
      { en: 'question', cn: '问题' },
      { en: 'quickly', cn: '快速地' },
      { en: 'realize', cn: '意识到' },
      { en: 'reason', cn: '原因' },
      { en: 'receive', cn: '接收' },
      { en: 'recognize', cn: '认出' },
      { en: 'recommend', cn: '推荐' },
      { en: 'regular', cn: '规律的' },
      { en: 'remember', cn: '记得' },
      { en: 'respect', cn: '尊重' },
      { en: 'responsible', cn: '负责任的' },
      { en: 'result', cn: '结果' },
      { en: 'return', cn: '返回' },
      { en: 'science', cn: '科学' },
      { en: 'season', cn: '季节' },
      { en: 'second', cn: '第二' },
      { en: 'several', cn: '几个' },
      { en: 'similar', cn: '相似的' },
      { en: 'simple', cn: '简单的' },
      { en: 'situation', cn: '情况' },
      { en: 'society', cn: '社会' },
      { en: 'special', cn: '特别的' },
      { en: 'specific', cn: '具体的' },
      { en: 'speech', cn: '演讲' },
      { en: 'straight', cn: '直的' },
      { en: 'strange', cn: '奇怪的' },
      { en: 'student', cn: '学生' },
      { en: 'subject', cn: '科目' },
      { en: 'success', cn: '成功' },
      { en: 'suddenly', cn: '突然地' },
      { en: 'suggest', cn: '建议' },
      { en: 'support', cn: '支持' },
      { en: 'surprise', cn: '惊喜' },
      { en: 'surround', cn: '环绕' },
      { en: 'terrible', cn: '可怕的' },
      { en: 'therefore', cn: '因此' },
      { en: 'though', cn: '虽然' },
      { en: 'through', cn: '通过' },
      { en: 'together', cn: '一起' },
      { en: 'tomorrow', cn: '明天' },
      { en: 'tonight', cn: '今晚' },
      { en: 'toward', cn: '朝向' },
      { en: 'traffic', cn: '交通' },
      { en: 'trouble', cn: '麻烦' },
      { en: 'understand', cn: '理解' },
      { en: 'usually', cn: '通常' },
      { en: 'various', cn: '各种各样的' },
      { en: 'village', cn: '村庄' },
      { en: 'visitor', cn: '访客' },
      { en: 'weather', cn: '天气' },
      { en: 'welcome', cn: '欢迎' },
      { en: 'whether', cn: '是否' },
      { en: 'without', cn: '没有' },
      { en: 'wonder', cn: '想知道' },
      { en: 'yesterday', cn: '昨天' }
    ],
    semester2: [
      { en: 'festival', cn: '节日' },
      { en: 'geography', cn: '地理' },
      { en: 'humanity', cn: '人性' },
      { en: 'industry', cn: '工业' },
      { en: 'justice', cn: '正义' },
      { en: 'knowledge', cn: '知识' },
      { en: 'laboratory', cn: '实验室' },
      { en: 'management', cn: '管理' },
      { en: 'necessary', cn: '必要的' },
      { en: 'observation', cn: '观察' },
      { en: 'participate', cn: '参与' },
      { en: 'quality', cn: '质量' },
      { en: 'recommend', cn: '推荐' },
      { en: 'scientific', cn: '科学的' },
      { en: 'technology', cn: '技术' },
      { en: 'universe', cn: '宇宙' },
      { en: 'valuable', cn: '有价值的' },
      { en: 'wonderful', cn: '精彩的' },
      { en: 'youth', cn: '青春' },
      { en: 'zoology', cn: '动物学' },
      { en: 'ability', cn: '能力' },
      { en: 'benefit', cn: '好处' },
      { en: 'challenge', cn: '挑战' },
      { en: 'determine', cn: '决定' },
      { en: 'encourage', cn: '鼓励' },
      { en: 'familiar', cn: '熟悉的' },
      { en: 'gradually', cn: '逐渐地' },
      { en: 'horizon', cn: '地平线' },
      { en: 'influence', cn: '影响' },
      { en: 'journey', cn: '旅程' },
      { en: 'landscape', cn: '风景' },
      { en: 'method', cn: '方法' },
      { en: 'nutrition', cn: '营养' },
      { en: 'opportunity', cn: '机会' },
      { en: 'perspective', cn: '观点' },
      { en: 'quantity', cn: '数量' },
      { en: 'relationship', cn: '关系' },
      { en: 'solution', cn: '解决方案' },
      { en: 'tradition', cn: '传统' },
      { en: 'unique', cn: '独特的' },
      { en: 'volunteer', cn: '志愿者' },
      { en: 'wisdom', cn: '智慧' },
      { en: 'anxious', cn: '焦虑的' },
      { en: 'brilliant', cn: '辉煌的' },
      { en: 'concentrate', cn: '集中' },
      { en: 'disappoint', cn: '使失望' },
      { en: 'embarrass', cn: '使尴尬' },
      { en: 'fortunate', cn: '幸运的' },
      { en: 'grateful', cn: '感激的' },
      { en: 'hesitate', cn: '犹豫' },
      { en: 'incredible', cn: '难以置信的' },
      { en: 'jealous', cn: '嫉妒的' },
      { en: 'magnificent', cn: '壮丽的' },
      { en: 'numerous', cn: '众多的' },
      { en: 'overcome', cn: '克服' },
      { en: 'persuade', cn: '说服' },
      { en: 'remarkable', cn: '非凡的' },
      { en: 'sensitive', cn: '敏感的' },
      { en: 'tremendous', cn: '巨大的' },
      { en: 'ultimate', cn: '最终的' },
      { en: 'valuable', cn: '有价值的' },
      { en: 'worthwhile', cn: '值得的' }
    ]
  },
  grade8: {
    semester1: [
      { en: 'agriculture', cn: '农业' },
      { en: 'broadcast', cn: '广播' },
      { en: 'commerce', cn: '商业' },
      { en: 'diplomat', cn: '外交官' },
      { en: 'engineer', cn: '工程师' },
      { en: 'abroad', cn: '国外' },
      { en: 'accept', cn: '接受' },
      { en: 'accident', cn: '事故' },
      { en: 'active', cn: '活跃的' },
      { en: 'actually', cn: '实际上' },
      { en: 'advantage', cn: '优势' },
      { en: 'advertisement', cn: '广告' },
      { en: 'advice', cn: '建议' },
      { en: 'affect', cn: '影响' },
      { en: 'afraid', cn: '害怕的' },
      { en: 'against', cn: '反对' },
      { en: 'age', cn: '年龄' },
      { en: 'agree', cn: '同意' },
      { en: 'ahead', cn: '在前面' },
      { en: 'air', cn: '空气' },
      { en: 'allow', cn: '允许' },
      { en: 'almost', cn: '几乎' },
      { en: 'alone', cn: '独自' },
      { en: 'along', cn: '沿着' },
      { en: 'already', cn: '已经' },
      { en: 'also', cn: '也' },
      { en: 'although', cn: '虽然' },
      { en: 'always', cn: '总是' },
      { en: 'among', cn: '在...之中' },
      { en: 'amount', cn: '数量' }
    ],
    semester2: [
      { en: 'finance', cn: '金融' },
      { en: 'geology', cn: '地质学' },
      { en: 'heritage', cn: '遗产' },
      { en: 'industry', cn: '工业' },
      { en: 'journal', cn: '日志' }
    ]
  },
  grade9: {
    semester1: [
      { en: 'achievement', cn: '成就' },
      { en: 'breakthrough', cn: '突破' },
      { en: 'conservation', cn: '保护' },
      { en: 'development', cn: '发展' },
      { en: 'environment', cn: '环境' }
    ],
    semester2: [
      { en: 'foundation', cn: '基础' },
      { en: 'generation', cn: '世代' },
      { en: 'hypothesis', cn: '假设' },
      { en: 'innovation', cn: '创新' },
      { en: 'judgment', cn: '判断' }
    ]
  }
};
