// 人教版英语单词数据
const wordData = {
  grade1: {
    semester1: [
      // Unit 1
      { en: 'book', cn: '书，书本' },
      { en: 'ruler', cn: '尺子' },
      { en: 'pencil', cn: '铅笔' },
      { en: 'schoolbag', cn: '书包' },
      { en: 'teacher', cn: '教师' },
      { en: 'have', cn: '有' },
      { en: 'a', cn: '一（个）' },
      // Unit 2
      { en: 'face', cn: '脸' },
      { en: 'ear', cn: '耳朵' },
      { en: 'eye', cn: '眼睛' },
      { en: 'nose', cn: '鼻子' },
      { en: 'mouth', cn: '嘴巴' },
      { en: 'this', cn: '这（个）' },
      { en: 'is', cn: '是' },
      { en: 'my', cn: '我的' },
      // Unit 3
      { en: 'dog', cn: '狗' },
      { en: 'bird', cn: '鸟' },
      { en: 'tiger', cn: '老虎' },
      { en: 'monkey', cn: '猴子' },
      { en: 'cat', cn: '猫' },
      { en: 'what', cn: '什么' },
      { en: 'it', cn: '它' },
      // Unit 4
      { en: 'one', cn: '一' },
      { en: 'two', cn: '二' },
      { en: 'three', cn: '三' },
      { en: 'four', cn: '四' },
      { en: 'five', cn: '五' },
      { en: 'six', cn: '六' },
      { en: 'seven', cn: '七' },
      { en: 'eight', cn: '八' },
      { en: 'nine', cn: '九' },
      { en: 'ten', cn: '十' },
      { en: 'how', cn: '多少' },
      { en: 'many', cn: '多的，许多的' },
      { en: 'are', cn: '是' },
      { en: 'there', cn: '（代替主语）' },
      // Unit 5
      { en: 'black', cn: '黑色；黑色的' },
      { en: 'yellow', cn: '黄色；黄色的' },
      { en: 'blue', cn: '蓝色；蓝色的' },
      { en: 'red', cn: '红色；红色的' },
      { en: 'green', cn: '绿色；绿色的' },
      { en: 'colour', cn: '颜色' },
      // Unit 6
      { en: 'apple', cn: '苹果' },
      { en: 'pear', cn: '梨' },
      { en: 'banana', cn: '香蕉' },
      { en: 'orange', cn: '柑橘；橙' },
      { en: 'do', cn: '（助动词）' },
      { en: 'you', cn: '你；你们' },
      { en: 'like', cn: '喜欢；喜爱' },
      { en: 'yes', cn: '是，是的' },
      { en: 'no', cn: '不，不是' }
    ],
    semester2: [
      { en: 'bag', cn: '包' },
      { en: 'bed', cn: '床' },
      { en: 'big', cn: '大的' },
      { en: 'bird', cn: '鸟' },
      { en: 'black', cn: '黑色的' },
      { en: 'blue', cn: '蓝色的' },
      { en: 'box', cn: '盒子' },
      { en: 'boy', cn: '男孩' },
      { en: 'cake', cn: '蛋糕' },
      { en: 'car', cn: '汽车' },
      { en: 'chair', cn: '椅子' },
      { en: 'cow', cn: '奶牛' },
      { en: 'desk', cn: '课桌' },
      { en: 'door', cn: '门' },
      { en: 'duck', cn: '鸭子' },
      { en: 'ear', cn: '耳朵' },
      { en: 'eye', cn: '眼睛' },
      { en: 'face', cn: '脸' },
      { en: 'fan', cn: '风扇' },
      { en: 'fish', cn: '鱼' },
      { en: 'five', cn: '五' },
      { en: 'four', cn: '四' },
      { en: 'girl', cn: '女孩' },
      { en: 'green', cn: '绿色的' },
      { en: 'hand', cn: '手' },
      { en: 'hat', cn: '帽子' },
      { en: 'head', cn: '头' },
      { en: 'hen', cn: '母鸡' },
      { en: 'home', cn: '家' },
      { en: 'horse', cn: '马' },
      { en: 'house', cn: '房子' },
      { en: 'ice', cn: '冰' },
      { en: 'jump', cn: '跳' },
      { en: 'kite', cn: '风筝' },
      { en: 'leg', cn: '腿' },
      { en: 'man', cn: '男人' },
      { en: 'map', cn: '地图' },
      { en: 'milk', cn: '牛奶' },
      { en: 'mom', cn: '妈妈' },
      { en: 'mouth', cn: '嘴' },
      { en: 'nine', cn: '九' },
      { en: 'nose', cn: '鼻子' },
      { en: 'one', cn: '一' },
      { en: 'pen', cn: '钢笔' },
      { en: 'pig', cn: '猪' },
      { en: 'pink', cn: '粉色的' },
      { en: 'red', cn: '红色的' },
      { en: 'run', cn: '跑' },
      { en: 'seven', cn: '七' },
      { en: 'ship', cn: '船' },
      { en: 'six', cn: '六' },
      { en: 'sofa', cn: '沙发' },
      { en: 'sun', cn: '太阳' },
      { en: 'ten', cn: '十' },
      { en: 'three', cn: '三' },
      { en: 'toy', cn: '玩具' },
      { en: 'tree', cn: '树' },
      { en: 'two', cn: '二' },
      { en: 'white', cn: '白色的' },
      { en: 'window', cn: '窗户' },
      { en: 'yellow', cn: '黄色的' },
      { en: 'zoo', cn: '动物园' }
    ]
  },
  grade2: {
    semester1: [
      { en: 'family', cn: '家庭' },
      { en: 'father', cn: '父亲；爸爸' },
      { en: 'mother', cn: '母亲；妈妈' },
      { en: 'brother', cn: '兄；弟' },
      { en: 'sister', cn: '姐；妹' },
      { en: 'grandmother', cn: '（外）祖母' },
      { en: 'grandfather', cn: '（外）祖父' },
      { en: 'who', cn: '谁' },
      { en: 'he', cn: '他' },
      { en: 'she', cn: '她' },
      { en: 'classmate', cn: '同班同学' },
      { en: 'friend', cn: '朋友' },
      { en: 'woman', cn: '女人' },
      { en: 'girl', cn: '女孩' },
      { en: 'man', cn: '男人' },
      { en: 'boy', cn: '男孩' },
      { en: 'look', cn: '看；瞧' },
      { en: 'his', cn: '他的' },
      { en: 'name', cn: '名字' },
      { en: 'her', cn: '她的' },
      { en: 'or', cn: '还是' },
      { en: 'big', cn: '大的' },
      { en: 'tall', cn: '高的' },
      { en: 'pretty', cn: '漂亮的' },
      { en: 'thin', cn: '瘦的' },
      { en: 'short', cn: '矮的；短的' },
      { en: 'handsome', cn: '英俊的' },
      { en: 'new', cn: '新的' },
      { en: 'does', cn: '（助动词）' },
      { en: 'bookshop', cn: '书店' },
      { en: 'zoo', cn: '动物园' },
      { en: 'school', cn: '学校' },
      { en: 'supermarket', cn: '超市' },
      { en: 'park', cn: '公园' },
      { en: 'hospital', cn: '医院' },
      { en: 'go', cn: '去' },
      { en: 'to', cn: '向，朝' },
      { en: 'grass', cn: '草' },
      { en: 'tree', cn: '树' },
      { en: 'flower', cn: '花' },
      { en: 'boat', cn: '小船' },
      { en: 'lake', cn: '湖' },
      { en: 'hill', cn: '小山' },
      { en: 'Christmas', cn: '圣诞节' },
      { en: 'Father Christmas', cn: '圣诞老人' },
      { en: 'Christmas tree', cn: '圣诞树' },
      { en: 'card', cn: '贺卡' },
      { en: 'present', cn: '礼物' },
      { en: 'New Year', cn: '新年' },
      { en: 'merry', cn: '高兴的' },
      { en: 'too', cn: '也' },
      { en: 'here', cn: '这儿' },
      { en: 'for', cn: '（表示接受某事物或从某事物中获益的人）' },
      { en: 'thank', cn: '谢谢' },
      { en: 'happy', cn: '快乐的' }
    ],
    semester2: [
      // Unit 1 Playtime
      { en: 'play football', cn: '踢足球' },
      { en: 'fly a kite', cn: '放风筝' },
      { en: 'ride a bike', cn: '骑自行车' },
      { en: 'make a model plane', cn: '做飞机模型' },
      { en: 'swim', cn: '游泳' },
      { en: 'make a snowman', cn: '堆雪人' },
      { en: 'can\'t', cn: '不能，不会' },
      
      // Unit 2 Weather
      { en: 'rainy', cn: '下雨的' },
      { en: 'cloudy', cn: '多云的' },
      { en: 'snowy', cn: '下雪的' },
      { en: 'windy', cn: '刮风的' },
      { en: 'sunny', cn: '晴朗的' },
      { en: 'umbrella', cn: '雨伞' },
      { en: 'weather', cn: '天气' },
      { en: 'wow', cn: '哇' },
      { en: 'let\'s', cn: '让我们' },
      
      // Unit 3 Season
      { en: 'spring', cn: '春天' },
      { en: 'summer', cn: '夏天' },
      { en: 'autumn', cn: '秋天' },
      { en: 'winter', cn: '冬天' },
      { en: 'hot', cn: '炎热的' },
      { en: 'warm', cn: '温暖的' },
      { en: 'cool', cn: '凉爽的' },
      { en: 'favourite', cn: '最喜欢的' },
      { en: 'cold', cn: '寒冷的' },
      { en: 'season', cn: '季节' },
      
      // Unit 4 Time
      { en: 'eleven', cn: '十一' },
      { en: 'twelve', cn: '十二' },
      { en: 'thirteen', cn: '十三' },
      { en: 'fourteen', cn: '十四' },
      { en: 'fifteen', cn: '十五' },
      { en: 'twenty', cn: '二十' },
      { en: 'thirty', cn: '三十' },
      { en: 'forty', cn: '四十' },
      { en: 'fifty', cn: '五十' },
      { en: 'time', cn: '时间' },
      { en: 'playtime', cn: '游戏时间，课间休息时间' },
      
      // Unit 5 My Day
      { en: 'get up', cn: '起床' },
      { en: 'eat breakfast', cn: '吃早饭' },
      { en: 'go to school', cn: '上学' },
      { en: 'eat lunch', cn: '吃午饭' },
      { en: 'go home', cn: '回家' },
      { en: 'eat dinner', cn: '吃晚饭' },
      { en: 'go to bed', cn: '上床睡觉' },
      { en: 'when', cn: '什么时候，何时' },
      { en: 'every day', cn: '每天' },
      { en: 'at', cn: '在…… 点钟' },
      
      // Unit 6 My Weak
      { en: 'Sunday', cn: '星期天' },
      { en: 'Monday', cn: '星期一' },
      { en: 'Tuesday', cn: '星期二' },
      { en: 'Wednesday', cn: '星期三' },
      { en: 'Thursday', cn: '星期四' },
      { en: 'Friday', cn: '星期五' },
      { en: 'Saturday', cn: '星期六' },
      { en: 'today', cn: '今天' }
    ]
  },
  grade3: {
    semester1: [
      // Unit 1
      { en: 'hello', cn: '你好' },
      { en: 'hi', cn: '嗨' },
      { en: 'good morning', cn: '早上好' },
      { en: 'good afternoon', cn: '下午好' },
      { en: 'goodbye', cn: '再见' },
      { en: 'bye-bye', cn: '拜拜' },
      { en: 'see you', cn: '再见' },
      { en: 'thank you', cn: '谢谢你' },
      { en: 'thanks', cn: '谢谢' },
      { en: 'welcome', cn: '欢迎' },
      { en: 'sorry', cn: '对不起' },
      { en: 'excuse me', cn: '打扰一下' },
      
      // Unit 2
      { en: 'classroom', cn: '教室' },
      { en: 'library', cn: '图书馆' },
      { en: 'playground', cn: '操场' },
      { en: 'music room', cn: '音乐室' },
      { en: 'computer room', cn: '电脑室' },
      { en: 'art room', cn: '美术室' },
      { en: 'toilet', cn: '厕所' },
      { en: 'office', cn: '办公室' },
      { en: 'canteen', cn: '食堂' },
      { en: 'where', cn: '哪里' },
      { en: 'over there', cn: '在那里' },
      { en: 'here', cn: '这里' },
      
      // Unit 3
      { en: 'like', cn: '喜欢' },
      { en: 'dog', cn: '狗' },
      { en: 'pet', cn: '宠物' },
      { en: 'cat', cn: '猫' },
      { en: 'fish', cn: '鱼' },
      { en: 'bird', cn: '鸟' },
      { en: 'rabbit', cn: '兔子' },
      { en: 'go', cn: '去' },
      { en: 'zoo', cn: '动物园' },
      { en: 'fox', cn: '狐狸' },
      { en: 'Miss', cn: '(学生对女教师的称呼); 女士' },
      { en: 'panda', cn: '大熊猫' },
      { en: 'red panda', cn: '小熊猫' },
      { en: 'cute', cn: '可爱的' },
      { en: 'monkey', cn: '猴子' },
      { en: 'tiger', cn: '老虎' },
      { en: 'elephant', cn: '大象' },
      { en: 'lion', cn: '狮子' },
      { en: 'giraffe', cn: '长颈鹿' },
      { en: 'tall', cn: '高的' },
      { en: 'fast', cn: '快的' },
      
      // Unit 4
      { en: 'head', cn: '头' },
      { en: 'hair', cn: '头发' },
      { en: 'face', cn: '脸' },
      { en: 'eye', cn: '眼睛' },
      { en: 'ear', cn: '耳朵' },
      { en: 'nose', cn: '鼻子' },
      { en: 'mouth', cn: '嘴巴' },
      { en: 'arm', cn: '手臂' },
      { en: 'hand', cn: '手' },
      { en: 'finger', cn: '手指' },
      { en: 'leg', cn: '腿' },
      { en: 'foot', cn: '脚' },
      { en: 'body', cn: '身体' },
      
      // Unit 5
      { en: 'shirt', cn: '衬衫' },
      { en: 'T-shirt', cn: 'T恤' },
      { en: 'dress', cn: '连衣裙' },
      { en: 'skirt', cn: '裙子' },
      { en: 'pants', cn: '裤子' },
      { en: 'shorts', cn: '短裤' },
      { en: 'shoes', cn: '鞋子' },
      { en: 'socks', cn: '袜子' },
      { en: 'hat', cn: '帽子' },
      { en: 'coat', cn: '外套' },
      { en: 'sweater', cn: '毛衣' },
      { en: 'jacket', cn: '夹克' },
      
      // Unit 6
      { en: 'family', cn: '家庭' },
      { en: 'father', cn: '父亲' },
      { en: 'mother', cn: '母亲' },
      { en: 'parents', cn: '父母' },
      { en: 'brother', cn: '兄弟' },
      { en: 'sister', cn: '姐妹' },
      { en: 'grandfather', cn: '祖父' },
      { en: 'grandmother', cn: '祖母' },
      { en: 'uncle', cn: '叔叔' },
      { en: 'aunt', cn: '阿姨' },
      { en: 'cousin', cn: '堂兄弟姐妹' },
      { en: 'baby', cn: '婴儿' }
    ],
    semester2: [
      // Unit 1
      { en: 'where', cn: '在哪里' },
      { en: 'from', cn: '来自' },
      { en: 'country', cn: '国家' },
      { en: 'city', cn: '城市' },
      { en: 'town', cn: '城镇' },
      { en: 'village', cn: '村庄' },
      { en: 'live', cn: '居住' },
      { en: 'street', cn: '街道' },
      { en: 'address', cn: '地址' },
      
      // Unit 2
      { en: 'has', cn: '有' },
      { en: 'long', cn: '长的' },
      { en: 'short', cn: '短的' },
      { en: 'big', cn: '大的' },
      { en: 'small', cn: '小的' },
      { en: 'tall', cn: '高的' },
      { en: 'heavy', cn: '重的' },
      { en: 'light', cn: '轻的' },
      { en: 'strong', cn: '强壮的' },
      { en: 'weak', cn: '虚弱的' },
      { en: 'young', cn: '年轻的' },
      { en: 'old', cn: '年老的' },
      
      // Unit 3
      { en: 'eraser', cn: '橡皮' },
      { en: 'find', cn: '找到；找回' },
      { en: 'ruler', cn: '尺子' },
      { en: 'pen', cn: '钢笔' },
      { en: 'pencil', cn: '铅笔' },
      { en: 'book', cn: '书；书籍' },
      { en: 'bag', cn: '包；袋' },
      { en: 'paper', cn: '纸' },
      { en: 'these', cn: '这些' },
      { en: 'see', cn: '看见' },
      { en: 'smell', cn: '闻（气味）' },
      { en: 'taste', cn: '尝（味道）' },
      { en: 'hear', cn: '听见；听到' },
      { en: 'touch', cn: '触摸；碰' },
      { en: 'sense', cn: '感官；感觉（听觉、视觉、味觉、嗅觉、触觉）' },
      { en: 'learn', cn: '学；学习' },
      { en: 'nose', cn: '鼻；鼻子' },
      { en: 'tongue', cn: '舌；舌头' },
      { en: 'class', cn: '课；班级' },
      { en: 'computer', cn: '计算机；电脑' },
      
      // Unit 4
      { en: 'breakfast', cn: '早餐；早饭' },
      { en: 'time', cn: '时间' },
      { en: 'bread', cn: '面包' },
      { en: 'egg', cn: '（作食物用的）蛋；鸡蛋' },
      { en: 'milk', cn: '（牛、羊等的）奶' },
      { en: 'noodle', cn: '（常用复数）面条' },
      { en: 'juice', cn: '果汁' },
      { en: 'rice', cn: '大米' },
      { en: 'meat', cn: '肉' },
      { en: 'vegetable', cn: '蔬菜' },
      { en: 'healthy', cn: '健康的' },
      { en: 'plate', cn: '盘子' },
      { en: 'soup', cn: '汤' },
      { en: 'fruit', cn: '水果' },
      { en: 'colourful', cn: '五彩缤纷的' },
      { en: 'candy', cn: '糖果' },
      { en: 'yummy', cn: '很好吃的' },
      
      // Unit 5
      { en: 'at', cn: '在（某处）' },
      { en: 'home', cn: '家；住所' },
      { en: 'boat', cn: '小船；舟' },
      { en: 'cool', cn: '（同时具与众不同的）酷的；绝妙的' },
      { en: 'keep', cn: '保有；留着' },
      { en: 'ball', cn: '球' },
      { en: 'doll', cn: '玩偶；玩具娃娃' },
      { en: 'car', cn: '小汽车；轿车' },
      { en: 'on', cn: '（放置、附着）在……上' },
      { en: 'shelf', cn: '架子' },
      { en: 'in', cn: '在……内；在……中' },
      { en: 'box', cn: '盒子' },
      { en: 'now', cn: '现在' },
      { en: 'cap', cn: '帽子' },
      { en: 'map', cn: '地图' },
      { en: 'under', cn: '在（表示、遮盖）……下面' },
      { en: 'still', cn: '还是；仍然' },
      { en: 'put', cn: '放；安放' },
      
      // Unit 6
      { en: 'fifteen', cn: '十五' },
      { en: 'twelve', cn: '十二' },
      { en: 'fourteen', cn: '十四' },
      { en: 'thirteen', cn: '十三' },
      { en: 'eleven', cn: '十一' },
      { en: 'choose', cn: '选择；挑选' },
      { en: 'twenty', cn: '二十' },
      { en: 'seventeen', cn: '十七' },
      { en: 'sixteen', cn: '十六' },
      { en: 'eighteen', cn: '十八' },
      { en: 'nineteen', cn: '十九' },
      { en: 'save', cn: '储蓄；积攒' },
      { en: 'spend', cn: '用；花（钱）' },
      { en: 'piggy bank', cn: '猪形储钱罐' },
      { en: 'pay', cn: '付费' },
      { en: 'back', cn: '回到原处' },
      
      // 保留原有单词
      { en: 'grass', cn: '草' },
      { en: 'house', cn: '房子' },
      { en: 'island', cn: '岛屿' },
      { en: 'jacket', cn: '夹克' },
      { en: 'kitchen', cn: '厨房' }
    ]
  },
  grade4: {
    semester1: [
      // Unit 1 My Classroom
      { en: 'classroom', cn: '教室' },
      { en: 'blackboard', cn: '黑板' },
      { en: 'whiteboard', cn: '白板' },
      { en: 'desk', cn: '课桌' },
      { en: 'chair', cn: '椅子' },
      { en: 'bookshelf', cn: '书架' },
      { en: 'computer', cn: '电脑' },
      { en: 'map', cn: '地图' },
      { en: 'clock', cn: '时钟' },
      { en: 'calendar', cn: '日历' },
      { en: 'picture', cn: '图片' },
      { en: 'light', cn: '灯' },
      { en: 'door', cn: '门' },
      { en: 'window', cn: '窗户' },
      { en: 'floor', cn: '地板' },
      { en: 'wall', cn: '墙' },
      { en: 'clean', cn: '打扫' },
      { en: 'dirty', cn: '脏的' },
      { en: 'tidy', cn: '整洁的' },
      { en: 'messy', cn: '凌乱的' },
      
      // Unit 2 My School
      { en: 'school', cn: '学校' },
      { en: 'library', cn: '图书馆' },
      { en: 'playground', cn: '操场' },
      { en: 'gym', cn: '体育馆' },
      { en: 'music room', cn: '音乐教室' },
      { en: 'art room', cn: '美术教室' },
      { en: 'science lab', cn: '科学实验室' },
      { en: 'computer room', cn: '计算机教室' },
      { en: 'canteen', cn: '食堂' },
      { en: 'office', cn: '办公室' },
      { en: 'toilet', cn: '厕所' },
      { en: 'gate', cn: '大门' },
      { en: 'garden', cn: '花园' },
      { en: 'field', cn: '场地' },
      { en: 'basketball court', cn: '篮球场' },
      { en: 'football field', cn: '足球场' },
      
      // Unit 3 My Day
      { en: 'get up', cn: '起床' },
      { en: 'wash face', cn: '洗脸' },
      { en: 'brush teeth', cn: '刷牙' },
      { en: 'comb hair', cn: '梳头' },
      { en: 'have breakfast', cn: '吃早餐' },
      { en: 'go to school', cn: '去上学' },
      { en: 'have class', cn: '上课' },
      { en: 'have lunch', cn: '吃午餐' },
      { en: 'play sports', cn: '做运动' },
      { en: 'go home', cn: '回家' },
      { en: 'do homework', cn: '做作业' },
      { en: 'have dinner', cn: '吃晚餐' },
      { en: 'watch TV', cn: '看电视' },
      { en: 'read books', cn: '读书' },
      { en: 'go to bed', cn: '上床睡觉' },
      { en: 'time', cn: '时间' },
            
      // Unit 4 My Hobbies
      { en: 'hobby', cn: '爱好' },
      { en: 'hobbies', cn: '爱好(复数)' },
      { en: 'like', cn: '喜欢' },
      { en: 'love', cn: '热爱' },
      { en: 'enjoy', cn: '享受' },
      { en: 'play football', cn: '踢足球' },
      { en: 'play basketball', cn: '打篮球' },
      { en: 'play volleyball', cn: '打排球' },
      { en: 'play tennis', cn: '打网球' },
      { en: 'play table tennis', cn: '打乒乓球' },
      { en: 'play the piano', cn: '弹钢琴' },
      { en: 'play the violin', cn: '拉小提琴' },
      { en: 'play the guitar', cn: '弹吉他' },
      { en: 'sing', cn: '唱歌' },
      { en: 'dance', cn: '跳舞' },
      { en: 'draw', cn: '画画' },
      { en: 'paint', cn: '绘画' },
      { en: 'read', cn: '阅读' },
      { en: 'write', cn: '写作' },
      { en: 'swim', cn: '游泳' },
      { en: 'run', cn: '跑步' },
      { en: 'jump', cn: '跳跃' },
      { en: 'ride a bike', cn: '骑自行车' },
      { en: 'fly a kite', cn: '放风筝' },
      { en: 'collect stamps', cn: '集邮' },
      { en: 'take photos', cn: '拍照' },
      { en: 'watch movies', cn: '看电影' },
      { en: 'listen to music', cn: '听音乐' },
      
      // Unit 5 My Friends
      { en: 'friend', cn: '朋友' },
      { en: 'classmate', cn: '同学' },
      { en: 'boy', cn: '男孩' },
      { en: 'girl', cn: '女孩' },
      { en: 'tall', cn: '高的' },
      { en: 'short', cn: '矮的' },
      { en: 'fat', cn: '胖的' },
      { en: 'thin', cn: '瘦的' },
      { en: 'strong', cn: '强壮的' },
      { en: 'weak', cn: '弱的' },
      { en: 'young', cn: '年轻的' },
      { en: 'old', cn: '年老的' },
      { en: 'handsome', cn: '英俊的' },
      { en: 'beautiful', cn: '美丽的' },
      { en: 'pretty', cn: '漂亮的' },
      { en: 'cute', cn: '可爱的' },
      { en: 'clever', cn: '聪明的' },
      { en: 'smart', cn: '聪明的' },
      { en: 'kind', cn: '友善的' },
      { en: 'friendly', cn: '友好的' },
      { en: 'helpful', cn: '乐于助人的' },
      { en: 'funny', cn: '有趣的' },
      { en: 'quiet', cn: '安静的' },
      { en: 'shy', cn: '害羞的' },
      { en: 'active', cn: '活跃的' },
      
      // Unit 6 My Family
      { en: 'family', cn: '家庭' },
      { en: 'father', cn: '父亲' },
      { en: 'mother', cn: '母亲' },
      { en: 'parents', cn: '父母' },
      { en: 'brother', cn: '兄弟' },
      { en: 'sister', cn: '姐妹' },
      { en: 'grandfather', cn: '祖父' },
      { en: 'grandmother', cn: '祖母' },
      { en: 'uncle', cn: '叔叔' },
      { en: 'aunt', cn: '阿姨' },
      { en: 'cousin', cn: '堂兄弟姐妹' },
      { en: 'baby', cn: '婴儿' },
      { en: 'doctor', cn: '医生' },
      { en: 'teacher', cn: '教师' },
      { en: 'student', cn: '学生' },
      { en: 'worker', cn: '工人' },
      { en: 'farmer', cn: '农民' },
      { en: 'driver', cn: '司机' },
      { en: 'nurse', cn: '护士' },
      { en: 'policeman', cn: '警察' },
      { en: 'cook', cn: '厨师' },
      { en: 'singer', cn: '歌手' },
      { en: 'actor', cn: '演员' },
      { en: 'artist', cn: '艺术家' },
      { en: 'scientist', cn: '科学家' },
      { en: 'engineer', cn: '工程师' }
    ],
    semester2: [
      // Unit 1
      { en: 'first', cn: '第一' },
      { en: 'floor', cn: '楼层' },
      { en: 'second', cn: '第二' },
      { en: 'teachers\'office', cn: '教师办公室' },
      { en: 'library', cn: '图书馆' },
      { en: 'playground', cn: '操场' },
      { en: 'computer room', cn: '计算机房' },
      { en: 'art room', cn: '美术教室' },
      { en: 'music room', cn: '音乐教室' },
      { en: 'next to', cn: '紧邻；在……旁边' },
      { en: 'homework', cn: '作业' },
      { en: 'class', cn: '班；班级' },
      { en: 'forty', cn: '四十' },
      { en: 'way', cn: '方向' },
      
      // Unit 2
      { en: 'breakfast', cn: '早餐；早饭' },
      { en: 'English class', cn: '英语课' },
      { en: 'lunch', cn: '午餐；午饭' },
      { en: 'music class', cn: '音乐课' },
      { en: 'PE class', cn: '体育课' },
      { en: 'dinner', cn: '（中午或晚上的）正餐' },
      { en: 'get up', cn: '起床' },
      { en: 'go to school', cn: '去上学' },
      { en: 'go home', cn: '回家' },
      { en: 'go to bed', cn: '上床睡觉' },
      { en: 'over', cn: '结束' },
      { en: 'now', cn: '现在；目前' },
      { en: 'o\'clock', cn: '（表示整点）' },
      { en: 'kid', cn: '小孩' },
      { en: 'thirty', cn: '三十' },
      { en: 'hurry', cn: '匆忙' },
      { en: 'come', cn: '来；加油' },
      { en: 'just', cn: '精确一会儿' },
      
      // Unit 3
      { en: 'cold', cn: '寒冷的；冷的' },
      { en: 'cool', cn: '凉的；凉爽的' },
      { en: 'warm', cn: '温暖的；暖和的' },
      { en: 'hot', cn: '热的；炎热的' },
      { en: 'sunny', cn: '阳光充足的' },
      { en: 'windy', cn: '多风的；风大的' },
      { en: 'cloudy', cn: '阴天的；多云的' },
      { en: 'snowy', cn: '下雪（多）的' },
      { en: 'rainy', cn: '雨的；多雨的' },
      { en: 'outside', cn: '在户外' },
      { en: 'be careful', cn: '小心' },
      { en: 'weather', cn: '天气' },
      { en: 'New York', cn: '纽约' },
      { en: 'how about', cn: '怎么样？……情况如何？' },
      { en: 'degree', cn: '度；度数' },
      { en: 'world', cn: '世界' },
      { en: 'London', cn: '伦敦' },
      { en: 'Moscow', cn: '莫斯科' },
      { en: 'Singapore', cn: '新加坡（市）' },
      { en: 'Sydney', cn: '悉尼' },
      { en: 'fly', cn: '飞（风筝等）' },
      { en: 'love', cn: '爱你的' },
      
      // Unit 4
      { en: 'tomato', cn: '西红柿' },
      { en: 'potato', cn: '马铃薯；土豆' },
      { en: 'green beans', cn: '豆角；四季豆' },
      { en: 'carrot', cn: '胡萝卜' },
      { en: 'horse', cn: '马' },
      { en: 'cow', cn: '奶牛；奶牛' },
      { en: 'sheep', cn: '羊；绵羊' },
      { en: 'hen', cn: '母鸡' },
      { en: 'these', cn: '这些' },
      { en: 'yum', cn: '表示好吃或好味道的感叹词' },
      { en: 'animal', cn: '兽；动物' },
      { en: 'those', cn: '那些' },
      { en: 'garden', cn: '花园；菜园' },
      { en: 'farm', cn: '农场' },
      { en: 'goat', cn: '山羊' },
      { en: 'eat', cn: '吃' },
      
      // Unit 5
      { en: 'clothes', cn: '衣服；服装' },
      { en: 'pants', cn: '裤子' },
      { en: 'hat', cn: '（常指有边的）帽子' },
      { en: 'dress', cn: '连衣裙' },
      { en: 'skirt', cn: '女裙' },
      { en: 'coat', cn: '外衣；大衣' },
      { en: 'sweater', cn: '毛衣' },
      { en: 'sock', cn: '短袜' },
      { en: 'shorts', cn: '短裤' },
      { en: 'jacket', cn: '夹克衫' },
      { en: 'shirt', cn: '（尤指男士的）衬衫' },
      { en: 'yours', cn: '你的；你们的' },
      { en: 'whose', cn: '谁的' },
      { en: 'mine', cn: '我的' },
      { en: 'pack', cn: '收拾（行李）' },
      { en: 'wait', cn: '等待' },
      
      // Unit 6
      { en: 'glove', cn: '（分手指的）手套' },
      { en: 'scarf', cn: '围巾；披巾' },
      { en: 'umbrella', cn: '伞；雨伞' },
      { en: 'sunglasses', cn: '太阳镜' },
      { en: 'pretty', cn: '美观的；精致的' },
      { en: 'expensive', cn: '昂贵的；花钱多的' },
      { en: 'cheap', cn: '花钱少的；便宜的' },
      { en: 'nice', cn: '好的' },
      { en: 'try on', cn: '试穿' },
      { en: 'size', cn: '尺寸；号' },
      { en: 'of course', cn: '当然' },
      { en: 'too', cn: '太；过于' },
      { en: 'just', cn: '正好；恰好' },
      { en: 'how much', cn: '多少钱' },
      { en: 'eighty', cn: '八十' },
      { en: 'dollar', cn: '（美国、加拿大等国的货币单位）元' },
      { en: 'sale', cn: '特价销售；大减价' },
      { en: 'more', cn: '更多的' },
      { en: 'us', cn: '我们' }
    ]
  },
  grade5: {
    semester1: [
      { en: 'unit1', cn: '单元1' },
      { en: 'welcome', cn: '欢迎' },
      { en: 'back', cn: '回来' },
      { en: 'to', cn: '到' },
      { en: 'school', cn: '学校' },
      { en: 'nice', cn: '好的' },
      { en: 'meet', cn: '遇见' },
      { en: 'you', cn: '你' },
      { en: 'too', cn: '也' },
      { en: 'what', cn: '什么' },
      { en: 'grade', cn: '年级' },
      { en: 'are', cn: '是' },
      { en: 'in', cn: '在' },
      { en: 'I', cn: '我' },
      { en: 'am', cn: '是' },
      { en: 'fifth', cn: '第五' },
      { en: 'how', cn: '怎样' },
      { en: 'spell', cn: '拼写' },
      { en: 'name', cn: '名字' },
      { en: 'my', cn: '我的' },
      { en: 'is', cn: '是' },
      { en: 'unit2', cn: '单元2' },
      { en: 'this', cn: '这个' },
      { en: 'our', cn: '我们的' },
      { en: 'classroom', cn: '教室' },
      { en: 'look', cn: '看' },
      { en: 'at', cn: '在' },
      { en: 'new', cn: '新的' },
      { en: 'it', cn: '它' },
      { en: 'has', cn: '有' },
      { en: 'computer', cn: '电脑' },
      { en: 'whiteboard', cn: '白板' },
      { en: 'bookshelf', cn: '书架' },
      { en: 'map', cn: '地图' },
      { en: 'clock', cn: '时钟' },
      { en: 'calendar', cn: '日历' },
      { en: 'picture', cn: '图片' },
      { en: 'desk', cn: '桌子' },
      { en: 'chair', cn: '椅子' },
      { en: 'unit3', cn: '单元3' },
      { en: 'where', cn: '哪里' },
      { en: 'they', cn: '他们' },
      { en: 'from', cn: '来自' },
      { en: 'Canada', cn: '加拿大' },
      { en: 'the', cn: '这个' },
      { en: 'USA', cn: '美国' },
      { en: 'UK', cn: '英国' },
      { en: 'Australia', cn: '澳大利亚' },
      { en: 'China', cn: '中国' },
      { en: 'Japan', cn: '日本' },
      { en: 'Korea', cn: '韩国' },
      { en: 'France', cn: '法国' },
      { en: 'Germany', cn: '德国' },
      { en: 'Italy', cn: '意大利' },
      { en: 'Russia', cn: '俄罗斯' },
      { en: 'unit4', cn: '单元4' },
      { en: 'when', cn: '什么时候' },
      { en: 'your', cn: '你的' },
      { en: 'birthday', cn: '生日' },
      { en: 'January', cn: '一月' },
      { en: 'February', cn: '二月' },
      { en: 'March', cn: '三月' },
      { en: 'April', cn: '四月' },
      { en: 'May', cn: '五月' },
      { en: 'June', cn: '六月' },
      { en: 'July', cn: '七月' },
      { en: 'August', cn: '八月' },
      { en: 'September', cn: '九月' },
      { en: 'October', cn: '十月' },
      { en: 'November', cn: '十一月' },
      { en: 'December', cn: '十二月' },
      { en: 'first', cn: '第一' },
      { en: 'second', cn: '第二' },
      { en: 'third', cn: '第三' },
      { en: 'fourth', cn: '第四' },
      { en: 'fifth', cn: '第五' },
      { en: 'unit5', cn: '单元5' },
      { en: 'do', cn: '做' },
      { en: 'like', cn: '喜欢' },
      { en: 'food', cn: '食物' },
      { en: 'hamburger', cn: '汉堡' },
      { en: 'hot dog', cn: '热狗' },
      { en: 'sandwich', cn: '三明治' },
      { en: 'French fries', cn: '薯条' },
      { en: 'chicken', cn: '鸡肉' },
      { en: 'salad', cn: '沙拉' },
      { en: 'noodles', cn: '面条' },
      { en: 'rice', cn: '米饭' },
      { en: 'vegetables', cn: '蔬菜' },
      { en: 'fruit', cn: '水果' },
      { en: 'ice cream', cn: '冰淇淋' },
      { en: 'milk', cn: '牛奶' },
      { en: 'juice', cn: '果汁' },
      { en: 'water', cn: '水' },
      { en: 'tea', cn: '茶' },
      { en: 'coffee', cn: '咖啡' },
      { en: 'unit6', cn: '单元6' },
      { en: 'would', cn: '将会' },
      { en: 'some', cn: '一些' },
      { en: 'please', cn: '请' },
      { en: 'here', cn: '这里' },
      { en: 'anything', cn: '任何事物' },
      { en: 'else', cn: '其他的' },
      { en: 'that', cn: '那个' },
      { en: 'all', cn: '全部' },
      { en: 'thanks', cn: '谢谢' },
      { en: 'welcome', cn: '欢迎' },
      { en: 'unit7', cn: '单元7' },
      { en: 'how', cn: '如何' },
      { en: 'much', cn: '多少' },
      { en: 'these', cn: '这些' },
      { en: 'pants', cn: '裤子' },
      { en: 'shirt', cn: '衬衫' },
      { en: 'sweater', cn: '毛衣' },
      { en: 'jacket', cn: '夹克' },
      { en: 'coat', cn: '外套' },
      { en: 'dress', cn: '连衣裙' },
      { en: 'skirt', cn: '裙子' },
      { en: 'shoes', cn: '鞋子' },
      { en: 'socks', cn: '袜子' },
      { en: 'hat', cn: '帽子' },
      { en: 'dollar', cn: '美元' },
      { en: 'yuan', cn: '元' },
      { en: 'unit8', cn: '单元8' },
      { en: 'whose', cn: '谁的' },
      { en: 'pen', cn: '钢笔' },
      { en: 'pencil', cn: '铅笔' },
      { en: 'pencil case', cn: '铅笔盒' },
      { en: 'ruler', cn: '尺子' },
      { en: 'eraser', cn: '橡皮' },
      { en: 'book', cn: '书' },
      { en: 'notebook', cn: '笔记本' },
      { en: 'schoolbag', cn: '书包' },
      { en: 'scissors', cn: '剪刀' },
      { en: 'glue', cn: '胶水' },
      { en: 'tape', cn: '胶带' },
      { en: 'stapler', cn: '订书机' },
      { en: 'his', cn: '他的' },
      { en: 'her', cn: '她的' },
      { en: 'their', cn: '他们的' }
    ],
    semester2: [
      { en: 'unit1', cn: '单元1' },
      { en: 'review', cn: '复习' },
      { en: 'remember', cn: '记得' },
      { en: 'forget', cn: '忘记' },
      { en: 'learn', cn: '学习' },
      { en: 'study', cn: '学习' },
      { en: 'practice', cn: '练习' },
      { en: 'speak', cn: '说' },
      { en: 'listen', cn: '听' },
      { en: 'read', cn: '读' },
      { en: 'write', cn: '写' },
      { en: 'unit2', cn: '单元2' },
      { en: 'hobby', cn: '爱好' },
      { en: 'hobbies', cn: '爱好(复数)' },
      { en: 'collect', cn: '收集' },
      { en: 'stamps', cn: '邮票' },
      { en: 'coins', cn: '硬币' },
      { en: 'shells', cn: '贝壳' },
      { en: 'model', cn: '模型' },
      { en: 'planes', cn: '飞机(复数)' },
      { en: 'cars', cn: '汽车(复数)' },
      { en: 'ships', cn: '船(复数)' },
      { en: 'unit3', cn: '单元3' },
      { en: 'weekend', cn: '周末' },
      { en: 'plan', cn: '计划' },
      { en: 'visit', cn: '参观' },
      { en: 'grandparents', cn: '祖父母' },
      { en: 'go', cn: '去' },
      { en: 'hiking', cn: '徒步旅行' },
      { en: 'shopping', cn: '购物' },
      { en: 'fishing', cn: '钓鱼' },
      { en: 'camping', cn: '露营' },
      { en: 'unit4', cn: '单元4' },
      { en: 'seasons', cn: '季节' },
      { en: 'spring', cn: '春天' },
      { en: 'summer', cn: '夏天' },
      { en: 'fall', cn: '秋天' },
      { en: 'autumn', cn: '秋天' },
      { en: 'winter', cn: '冬天' },
      { en: 'weather', cn: '天气' },
      { en: 'sunny', cn: '晴朗的' },
      { en: 'cloudy', cn: '多云的' },
      { en: 'windy', cn: '有风的' },
      { en: 'rainy', cn: '下雨的' },
      { en: 'snowy', cn: '下雪的' },
      { en: 'unit5', cn: '单元5' },
      { en: 'vacation', cn: '假期' },
      { en: 'travel', cn: '旅行' },
      { en: 'beach', cn: '海滩' },
      { en: 'mountain', cn: '山' },
      { en: 'lake', cn: '湖' },
      { en: 'forest', cn: '森林' },
      { en: 'desert', cn: '沙漠' },
      { en: 'island', cn: '岛屿' },
      { en: 'hotel', cn: '酒店' },
      { en: 'unit6', cn: '单元6' },
      { en: 'festival', cn: '节日' },
      { en: 'celebrate', cn: '庆祝' },
      { en: 'Christmas', cn: '圣诞节' },
      { en: 'New Year', cn: '新年' },
      { en: 'Spring Festival', cn: '春节' },
      { en: 'Lantern Festival', cn: '元宵节' },
      { en: 'Mid-Autumn Festival', cn: '中秋节' },
      { en: 'Dragon Boat Festival', cn: '端午节' },
      { en: 'Halloween', cn: '万圣节' },
      { en: 'Thanksgiving', cn: '感恩节' },
      { en: 'unit7', cn: '单元7' },
      { en: 'health', cn: '健康' },
      { en: 'exercise', cn: '锻炼' },
      { en: 'sports', cn: '运动' },
      { en: 'basketball', cn: '篮球' },
      { en: 'football', cn: '足球' },
      { en: 'volleyball', cn: '排球' },
      { en: 'tennis', cn: '网球' },
      { en: 'swimming', cn: '游泳' },
      { en: 'running', cn: '跑步' },
      { en: 'unit8', cn: '单元8' },
      { en: 'environment', cn: '环境' },
      { en: 'protect', cn: '保护' },
      { en: 'pollution', cn: '污染' },
      { en: 'recycle', cn: '回收' },
      { en: 'reduce', cn: '减少' },
      { en: 'reuse', cn: '重复使用' },
      { en: 'save', cn: '节约' },
      { en: 'energy', cn: '能源' },
      { en: 'water', cn: '水' },
      { en: 'earth', cn: '地球' }
    ]
  },
  grade6: {
    semester1: [
      { en: 'science', cn: '科学' },
      { en: 'museum', cn: '博物馆' },
      { en: 'post office', cn: '邮局' },
      { en: 'bookstore', cn: '书店' },
      { en: 'cinema', cn: '电影院' },
      { en: 'hospital', cn: '医院' },
      { en: 'crossing', cn: '十字路口' },
      { en: 'turn', cn: '转弯' },
      { en: 'left', cn: '左' },
      { en: 'straight', cn: '笔直地' },
      { en: 'right', cn: '右' },
      { en: 'ask', cn: '问' },
      { en: 'sir', cn: '先生' },
      { en: 'interesting', cn: '有趣的' },
      { en: 'Italian', cn: '意大利的' },
      { en: 'restaurant', cn: '餐馆' },
      { en: 'pizza', cn: '比萨饼' },
      { en: 'street', cn: '大街；街道' },
      { en: 'get', cn: '到达' },
      { en: 'GPS', cn: '全球（卫星）定位系统' },
      { en: 'gave', cn: '给供；交给' },
      { en: 'feature', cn: '特点' },
      { en: 'follow', cn: '跟着' },
      { en: 'far', cn: '较远的' },
      { en: 'tell', cn: '告诉' },
      { en: 'on foot', cn: '步行' },
      { en: 'by', cn: '乘（表示方式）' },
      { en: 'bus', cn: '公共汽车' },
      { en: 'plane', cn: '飞机' },
      { en: 'taxi', cn: '出租汽车' },
      { en: 'ship', cn: '（大）船' },
      { en: 'subway', cn: '地铁' },
      { en: 'train', cn: '火车' },
      { en: 'slow', cn: '慢的' },
      { en: 'down', cn: '减少；降低' },
      { en: 'slow down', cn: '慢下来' },
      { en: 'stop', cn: '停下' },
      { en: 'Mrs', cn: '夫人' },
      { en: 'early', cn: '早到的' },
      { en: 'helmet', cn: '头盔' },
      { en: 'must', cn: '必须' },
      { en: 'wear', cn: '戴' },
      { en: 'attention', cn: '注意' },
      { en: 'pay attention to', cn: '注意' },
      { en: 'traffic', cn: '交通' },
      { en: 'traffic lights', cn: '交通信号灯' }
    ],
    semester2: [
      { en: 'weather', cn: '天气' },
      { en: 'sunny', cn: '晴朗的' },
      { en: 'cloudy', cn: '多云的' },
      { en: 'windy', cn: '有风的' },
      { en: 'rainy', cn: '下雨的' },
      { en: 'snowy', cn: '下雪的' },
      { en: 'hot', cn: '热的' },
      { en: 'cold', cn: '冷的' },
      { en: 'warm', cn: '温暖的' },
      { en: 'cool', cn: '凉爽的' },
      { en: 'temperature', cn: '温度' },
      { en: 'degree', cn: '度' },
      { en: 'season', cn: '季节' },
      { en: 'spring', cn: '春天' },
      { en: 'summer', cn: '夏天' },
      { en: 'autumn', cn: '秋天' },
      { en: 'winter', cn: '冬天' },
      { en: 'January', cn: '一月' },
      { en: 'February', cn: '二月' },
      { en: 'March', cn: '三月' },
      { en: 'April', cn: '四月' },
      { en: 'May', cn: '五月' },
      { en: 'June', cn: '六月' },
      { en: 'July', cn: '七月' },
      { en: 'August', cn: '八月' },
      { en: 'September', cn: '九月' },
      { en: 'October', cn: '十月' },
      { en: 'November', cn: '十一月' },
      { en: 'December', cn: '十二月' },
      { en: 'umbrella', cn: '雨伞' }
    ]
  },
  grade7: {
    semester1: [
      // P-Z
      { en: 'parent', cn: '父（母）亲' },
      { en: 'party', cn: '聚会；晚会' },
      { en: 'P.E.', cn: '体育' },
      { en: 'pear', cn: '梨' },
      { en: 'pen', cn: '笔；钢笔' },
      { en: 'pencil', cn: '铅笔' },
      { en: 'pencil box', cn: '铅笔盒；文具盒' },
      { en: 'phone', cn: '电话；电话机' },
      { en: 'photo', cn: '照片' },
      { en: 'picture', cn: '照片；图画' },
      { en: 'ping-pong', cn: '乒乓球' },
      { en: 'plane', cn: '飞机' },
      { en: 'play', cn: '参加（比赛或运动）；玩耍' },
      { en: 'player', cn: '播放机' },
      { en: 'please', cn: '请' },
      { en: 'P.M.', cn: '下午；午后' },
      { en: 'price', cn: '价格' },
      { en: 'purple', cn: '紫色（的）' },
      { en: 'question', cn: '问题' },
      { en: 'quilt', cn: '被子；床罩' },
      { en: 'radio', cn: '收音机；无线电广播' },
      { en: 'really', cn: '真正地；确实' },
      { en: 'red', cn: '红色（的）' },
      { en: 'relaxing', cn: '轻松的；令人放松的' },
      { en: 'rice', cn: '大米；米饭' },
      { en: 'right', cn: '正确的；适当的' },
      { en: 'ring', cn: '戒指' },
      { en: 'room', cn: '房间' },
      { en: 'ruler', cn: '尺；直尺' },
      { en: 'salad', cn: '沙拉' },
      { en: 'sale', cn: '特价销售；出售' },
      { en: 'same', cn: '相同的' },
      { en: 'Saturday', cn: '星期六' },
      { en: 'say', cn: '说；讲' },
      { en: 'school', cn: '学校' },
      { en: 'schoolbag', cn: '书包' },
      { en: 'science', cn: '科学' },
      { en: 'second', cn: '第二' },
      { en: 'see', cn: '理解；明白' },
      { en: 'See you!', cn: '再见！' },
      { en: 'sell', cn: '出售；销售；卖' },
      { en: 'September', cn: '九月' },
      { en: 'set', cn: '一套；一部；一组' },
      { en: 'seven', cn: '七' },
      { en: 'she', cn: '她' },
      { en: 'shoe', cn: '鞋' },
      { en: 'short', cn: '短的；矮的' },
      { en: 'shorts', cn: '短裤' },
      { en: 'sister', cn: '姐；妹' },
      { en: 'six', cn: '六' },
      { en: 'skirt', cn: '裙子' },
      { en: 'small', cn: '小的；小号的' },
      { en: 'so', cn: '引出评论或问题' },
      { en: 'soccer', cn: '（英式）足球' },
      { en: 'soccer ball', cn: '（英式）足球' },
      { en: 'sock', cn: '短袜' },
      { en: 'sofa', cn: '沙发' },
      { en: 'some', cn: '一些；某些' },
      { en: 'son', cn: '儿子' },
      { en: 'sound', cn: '听起来好像' },
      { en: 'spell', cn: '用字母拼；拼写' },
      { en: 'sport', cn: '体育运动' },
      { en: 'star', cn: '明星；星星' },
      { en: 'store', cn: '商店' },
      { en: 'strawberry', cn: '草莓' },
      { en: 'student', cn: '学生' },
      { en: 'subject', cn: '学科；科目' },
      { en: 'Sunday', cn: '星期日' },
      { en: 'sure', cn: '当然；肯定；一定' },
      { en: 'sweater', cn: '毛衣' },
      { en: 'table', cn: '桌子' },
      { en: 'take', cn: '拿下；拿；取' },
      { en: 'tape', cn: '磁带；录音带；录像带' },
      { en: 'tape player', cn: '录音机' },
      { en: 'teacher', cn: '老师；教师' },
      { en: 'telephone', cn: '电话；电话机' },
      { en: 'telephone/phone number', cn: '电话号码' },
      { en: 'ten', cn: '十' },
      { en: 'tennis', cn: '网球' },
      { en: 'term', cn: '学期' },
      { en: 'test', cn: '测验；检查' },
      { en: 'thank', cn: '感谢；谢谢' },
      { en: 'thank you for...', cn: '为……而感谢' },
      { en: 'thanks', cn: '感谢；谢谢' },
      { en: 'that', cn: '那；那个' },
      { en: 'the', cn: '指已提到或易领会到的人或事物' },
      { en: 'their', cn: '他（她、它）们的' },
      { en: 'them', cn: '他（她、它）们' },
      { en: 'then', cn: '那么' },
      { en: 'there', cn: '在；那里' },
      { en: 'these', cn: '这些' },
      { en: 'they', cn: '他（她、它）们' },
      { en: 'thing', cn: '东西；事情' },
      { en: 'think', cn: '认为；想；思考' },
      { en: 'think about', cn: '思考；想想' },
      { en: 'third', cn: '第三' },
      { en: 'thirteen', cn: '十三' },
      { en: 'thirty', cn: '三十' },
      { en: 'this', cn: '这；这个' },
      { en: 'those', cn: '那些' },
      { en: 'three', cn: '三' },
      { en: 'Thursday', cn: '星期四' },
      { en: 'tidy', cn: '整洁的；井井有条的' },
      { en: 'time', cn: '时间' },
      { en: 'to', cn: '表示动词为不定式' },
      { en: 'tomato', cn: '西红柿' },
      { en: 'too', cn: '也；又' },
      { en: 'trip', cn: '旅游；旅行' },
      { en: 'trousers', cn: '裤子' },
      { en: 'T-shirt', cn: 'T恤衫' },
      { en: 'Tuesday', cn: '星期二' },
      { en: 'TV', cn: '电视；电视机' },
      { en: 'twelfth', cn: '第十二' },
      { en: 'twelve', cn: '十二' },
      { en: 'twentieth', cn: '第二十' },
      { en: 'twenty', cn: '二十' },
      { en: 'two', cn: '二' },
      { en: 'uncle', cn: '叔父；伯父；舅父' },
      { en: 'under', cn: '在……下' },
      { en: 'us', cn: '我们' },
      { en: 'useful', cn: '有用的；有益的' },
      { en: 'vegetable', cn: '蔬菜' },
      { en: 'very', cn: '很；非常' },
      { en: 'volleyball', cn: '排球' },
      { en: 'want', cn: '需要；想要' },
      { en: 'watch', cn: '表；手表' },
      { en: 'watch TV', cn: '看电视' },
      { en: 'we', cn: '我们' },
      { en: 'Wednesday', cn: '星期三' },
      { en: 'week', cn: '周；星期' },
      { en: 'welcome', cn: '受欢迎的' },
      { en: 'well', cn: '嗯；好吧' },
      { en: 'what', cn: '什么' },
      { en: 'What about...?', cn: '询问信息或提出建议' },
      { en: 'when', cn: '什么时候' },
      { en: 'where', cn: '在哪里；到哪里' },
      { en: 'white', cn: '白色（的）' },
      { en: 'who', cn: '谁；什么人' },
      { en: 'why', cn: '为什么' },
      { en: 'with', cn: '和……一起；使用' },
      { en: 'woman', cn: '女子' },
      { en: 'yeah', cn: '是的；对' },
      { en: 'yellow', cn: '黄色（的）' },
      { en: 'yes', cn: '是的；可以' },
      { en: 'you', cn: '你；你们' },
      { en: 'You\'re welcome.', cn: '别客气。' },
      { en: 'your', cn: '你的；你们的' },
      { en: 'yours', cn: '你的；你们的' },
      { en: 'zero', cn: '零' },
      // A
      { en: 'a', cn: '一（个）' },
      { en: 'a pair of', cn: '一双' },
      { en: 'a set of', cn: '一套；一副；一组' },
      { en: 'about', cn: '关于' },
      { en: 'after', cn: '在……以后' },
      { en: 'afternoon', cn: '下午' },
      { en: 'all', cn: '所有的；全部的' },
      { en: 'always', cn: '总是' },
      { en: 'am', cn: '是' },
      { en: 'A.M.', cn: '上午' },
      { en: 'and', cn: '和；又；而' },
      { en: 'apple', cn: '苹果' },
      { en: 'April', cn: '四月' },
      { en: 'are', cn: '是' },
      { en: 'art', cn: '艺术；美术' },
      { en: 'ask', cn: '请求；要求；询问' },
      { en: 'ask ... for ...', cn: '请求；恳求（给予）' },
      { en: 'at', cn: '在（某时）；在（某处、某时刻或时段）' },
      { en: 'August', cn: '八月' },
      { en: 'aunt', cn: '姑母；姨母；伯母；婶母；舅母' },
      // B
      { en: 'bag', cn: '袋；包' },
      { en: 'ball', cn: '球' },
      { en: 'banana', cn: '香蕉' },
      { en: 'baseball', cn: '棒球' },
      { en: 'basketball', cn: '篮球' },
      { en: 'bat', cn: '球棒；球拍' },
      { en: 'be', cn: '变成' },
      { en: 'because', cn: '因为' },
      { en: 'bed', cn: '床' },
      { en: 'big', cn: '大的；大号的' },
      { en: 'birthday', cn: '生日' },
      { en: 'black', cn: '黑色（的）' },
      { en: 'blue', cn: '蓝色（的）' },
      { en: 'book', cn: '书' },
      { en: 'bookcase', cn: '书架；书柜' },
      { en: 'boring', cn: '没趣的；令人厌倦的' },
      { en: 'box', cn: '箱；盒' },
      { en: 'boy', cn: '男孩' },
      { en: 'bread', cn: '面包' },
      { en: 'breakfast', cn: '早餐；早饭' },
      { en: 'brother', cn: '兄；弟' },
      { en: 'brown', cn: '棕色（的）；褐色（的）' },
      { en: 'burger', cn: '汉堡包' },
      { en: 'busy', cn: '忙碌的；无暇的' },
      { en: 'but', cn: '但是' },
      { en: 'buy', cn: '购买；买' },
      { en: 'bye', cn: '再见' },
      // C
      { en: 'call', cn: '给（……）打电话' },
      { en: 'can', cn: '能；会' },
      { en: 'Can I help you?', cn: '我能帮您吗？' },
      { en: 'card', cn: '卡片' },
      { en: 'carrot', cn: '胡萝卜' },
      { en: 'chair', cn: '椅子' },
      { en: 'chicken', cn: '鸡肉' },
      { en: 'China', cn: '中国' },
      { en: 'Chinese', cn: '语文；汉语' },
      { en: 'class', cn: '班级；课' },
      { en: 'classmate', cn: '同班同学' },
      { en: 'classroom', cn: '教室' },
      { en: 'clock', cn: '时钟' },
      { en: 'clothes', cn: '衣服；服装' },
      { en: 'color', cn: '颜色' },
      { en: 'come', cn: '来；来到' },
      { en: 'come on', cn: '快点儿' },
      { en: 'computer', cn: '计算机；电脑' },
      { en: 'cool', cn: '妙极的；酷的' },
      { en: 'cousin', cn: '堂兄（弟、姐、妹）；表兄（弟、姐、妹）' },
      { en: 'cup', cn: '杯子' },
      // D
      { en: 'dad', cn: '爸爸' },
      { en: 'daughter', cn: '女儿' },
      { en: 'day', cn: '一天；一日；白天' },
      { en: 'dear', cn: '亲爱的' },
      { en: 'December', cn: '十二月' },
      { en: 'desk', cn: '书桌' },
      { en: 'dictionary', cn: '词典；字典' },
      { en: 'difficult', cn: '困难的' },
      { en: 'dinner', cn: '（中午或晚上吃的）正餐' },
      { en: 'do', cn: '（第三人称单数形式 does）用于构成否定句和疑问句；做；干' },
      { en: 'dog', cn: '狗' },
      { en: 'dollar', cn: '元（美国、加拿大等国的货币单位，符号为$）' },
      // E
      { en: 'easy', cn: '容易的；不费力的' },
      { en: 'eat', cn: '吃' },
      { en: 'egg', cn: '蛋；鸡蛋' },
      { en: 'eight', cn: '八' },
      { en: 'eighteen', cn: '十八' },
      { en: 'eighth', cn: '第八' },
      { en: 'eleven', cn: '十一' },
      { en: 'e-mail', cn: '电子邮件' },
      { en: 'English', cn: '英语' },
      { en: 'eraser', cn: '橡皮' },
      { en: 'evening', cn: '晚上；傍晚' },
      { en: 'everywhere', cn: '处处；到处；各个地方' },
      { en: 'excuse', cn: '原谅；宽恕' },
      { en: 'excuse me', cn: '劳驾；请原谅' },
      // F
      { en: 'family', cn: '家；家庭' },
      { en: 'fat', cn: '肥的；胖胖的' },
      { en: 'father', cn: '父亲；爸爸' },
      { en: 'favorite', cn: '特别喜爱的（人或事物）' },
      { en: 'February', cn: '二月' },
      { en: 'festival', cn: '（音乐、戏剧等的）会演节；节日' },
      { en: 'fifteen', cn: '十五' },
      { en: 'fifth', cn: '第五' },     
      { en: 'fine', cn: '健康的；美好的' },
      { en: 'finish', cn: '完成；做完' },
      { en: 'first', cn: '第一' },
      { en: 'five', cn: '五' },
      { en: 'food', cn: '食物' },
      { en: 'for', cn: '为了；给；对' },
      { en: 'for sure', cn: '无疑；肯定' },
      { en: 'four', cn: '四' },
      { en: 'free', cn: '空闲的' },
      { en: 'Friday', cn: '星期五' },
      { en: 'friend', cn: '朋友' },
      { en: 'from', cn: '（表示开始的时间）从……开始' },
      { en: 'from ... to ...', cn: '从……到……' },
      { en: 'fruit', cn: '水果' },
      { en: 'fun', cn: '有趣的；使人快乐的' },
      // G
      { en: 'game', cn: '游戏；运动；比赛' },
      { en: 'geography', cn: '地理（学）' },
      { en: 'get', cn: '去取（或带来）；得到' },
      { en: 'girl', cn: '女孩' },
      { en: 'go', cn: '去；走' },
      { en: 'good', cn: '好的' },
      { en: 'Good morning!', cn: '早上好！' },
      { en: 'Good afternoon!', cn: '下午好！' },
      { en: 'Good evening!', cn: '晚上好！' },
      { en: 'grandfather', cn: '（外）祖父；爷爷；外公；姥爷' },
      { en: 'grandma', cn: '（外）祖母；奶奶；外婆；姥姥' },
      { en: 'grandmother', cn: '（外）祖母；奶奶；外婆；姥姥' },
      { en: 'grandpa', cn: '（外）祖父；爷爷；外公；姥爷' },
      { en: 'grandparent', cn: '祖父（母）；外祖父（母）' },
      { en: 'great', cn: '美妙的；伟大的' },
      { en: 'green', cn: '绿色（的）' },
      // H
      { en: 'habit', cn: '习惯' },
      { en: 'hamburger', cn: '汉堡包' },
      { en: 'happy', cn: '愉快的；高兴的' },
      { en: 'Happy birthday!', cn: '生日快乐！' },
      { en: 'hat', cn: '帽子' },
      { en: 'have', cn: '经受；经历' },
      { en: 'have', cn: '有' },
      { en: 'Have a good day!', cn: '（表示祝愿）过得愉快！' },
      { en: 'Have a good time!', cn: '（表示祝愿）过得愉快！' },
      { en: 'he', cn: '他' },
      { en: 'head', cn: '头' },
      { en: 'healthy', cn: '健康的' },
      { en: 'hello', cn: '你好；喂' },
      { en: 'help', cn: '帮助；援助' },
      { en: 'her', cn: '她的' },
      { en: 'here', cn: '（用以介绍某人或某物）这就是；在这里' },
      { en: 'Here you are.', cn: '给你。' },
      { en: 'hers', cn: '她的' },
      { en: 'hi', cn: '（用于打招呼）嗨；喂' },
      { en: 'his', cn: '他的' },
      { en: 'history', cn: '历史' },
      { en: 'hour', cn: '小时' },
      { en: 'how', cn: '怎样；如何' },
      { en: 'How about ...?', cn: '（提出建议）……怎么样？' },
      { en: 'How are you?', cn: '你好吗？' },
      { en: 'How old ...?', cn: '……多大年纪？……几岁了？' },
      { en: 'How much ...?', cn: '（购物时）……多少钱？' },
      // I
      { en: 'I', cn: '我' },
      { en: 'ice-cream', cn: '冰激凌' },
      { en: 'ID card', cn: '学生卡；身份证' },
      { en: 'in', cn: '（表示使用语言、材料等）用；以' },
      { en: 'in', cn: '在……里' },
      { en: 'in English', cn: '用英语' },
      { en: 'interesting', cn: '有趣的' },
      { en: 'is', cn: '是' },
      { en: 'it', cn: '它' },
      // J
      { en: 'jacket', cn: '夹克衫；短上衣' },
      { en: 'January', cn: '一月' },
      { en: 'July', cn: '七月' },
      { en: 'June', cn: '六月' },
      // K
      { en: 'key', cn: '钥匙' },
      { en: 'know', cn: '知道；了解' },
      // L
      { en: 'last', cn: '最后的；末尾的' },
      { en: 'last name', cn: '姓' },
      { en: 'late', cn: '迟到' },
      { en: 'lesson', cn: '课；一节课' },
      { en: 'let', cn: '允许；让' },
      { en: 'library', cn: '图书馆' },
      { en: 'like', cn: '喜欢；喜爱' },
      { en: 'long', cn: '长的' },
      { en: 'look', cn: '看；看上去' },
      { en: 'lost', cn: '（动词lose的过去式）遗失；丢失' },
      { en: 'love', cn: '爱；喜爱' },
      { en: 'lunch', cn: '午餐' },
      // M
      { en: 'map', cn: '地图' },
      { en: 'March', cn: '三月' },
      { en: 'math', cn: '数学' },
      { en: 'May', cn: '五月' },
      { en: 'me', cn: '（宾格）我' },
      { en: 'meet', cn: '遇见；相遇' },
      { en: 'middle', cn: '中间的；中等的' },
      { en: 'middle school', cn: '中学；初中' },
      { en: 'milk', cn: '牛奶' },
      { en: 'mine', cn: '我的' },
      { en: 'model', cn: '模型' },
      { en: 'model plane', cn: '飞机模型' },
      { en: 'mom', cn: '妈妈' },
      { en: 'Monday', cn: '星期一' },
      { en: 'month', cn: '月；月份' },
      { en: 'morning', cn: '早晨；上午' },
      { en: 'mother', cn: '母亲；妈妈' },
      { en: 'Mr.', cn: '（用于男子的姓氏或姓名前）先生' },
      { en: 'Mrs.', cn: '（用于女子的姓氏或姓名前）太太；夫人' },
      { en: 'Ms.', cn: '（用于女子的姓氏或姓前，不指明婚否）女士' },
      { en: 'much', cn: '许多；大量；多少' },
      { en: 'music', cn: '音乐；乐曲' },
      { en: 'must', cn: '必须' },
      { en: 'my', cn: '我的' },
      // N
      { en: 'name', cn: '名字；名称' },
      { en: 'need', cn: '需要' },
      { en: 'next', cn: '下一个（的）；接下来（的）' },
      { en: 'nice', cn: '令人愉快的；宜人的' },
      { en: 'nine', cn: '九' },
      { en: 'ninth', cn: '第九' },
      { en: 'no', cn: '不；没有；不是' },
      { en: 'not', cn: '不；没有' },
      { en: 'notebook', cn: '笔记本' },
      { en: 'November', cn: '十一月' },
      { en: 'now', cn: '现在；目前' },
      { en: 'number', cn: '号码；数字' },
      // O
      { en: 'October', cn: '十月' },
      { en: 'of', cn: '属于（某人或某物）；关于（某人或某物）' },
      { en: 'oh', cn: '哦；啊' },
      { en: 'OK', cn: '好；可以' },
      { en: 'old', cn: '年老的；旧的' },
      { en: 'on', cn: '在……上' },
      { en: 'one', cn: '一' },
      { en: 'only', cn: '只；仅' },
      { en: 'orange', cn: '橙子' },
      { en: 'our', cn: '我们的' },
      // P
      { en: 'pair', cn: '一双；一对' },
      { en: 'pants', cn: '裤子' },
      { en: 'paper', cn: '纸' },
      { en: 'parent', cn: '父亲或母亲；双亲' },
      { en: 'park', cn: '公园' },
      { en: 'party', cn: '聚会；晚会' },
      { en: 'pen', cn: '钢笔' },
      { en: 'pencil', cn: '铅笔' },
      { en: 'pencil-case', cn: '铅笔盒' },
      { en: 'people', cn: '人；人们' },
      { en: 'photo', cn: '照片' },
      { en: 'picture', cn: '图画；照片' },
      { en: 'pink', cn: '粉红色（的）' },
      { en: 'place', cn: '地方；处所' },
      { en: 'plane', cn: '飞机' },
      { en: 'play', cn: '玩；打（球）；下（棋）' },
      { en: 'please', cn: '请' },
      { en: 'P.M.', cn: '下午' },
      { en: 'potato', cn: '土豆；马铃薯' },
      { en: 'present', cn: '礼物' },
      { en: 'purple', cn: '紫色（的）' },
      // Q
      { en: 'question', cn: '问题' },
      { en: 'quiet', cn: '安静的' },
      // R
      { en: 'rabbit', cn: '兔子' },
      { en: 'radio', cn: '收音机' },
      { en: 'rain', cn: '雨；下雨' },
      { en: 'read', cn: '读；阅读' },
      { en: 'really', cn: '真正地；确实' },
      { en: 'red', cn: '红色（的）' },
      { en: 'rice', cn: '米饭' },
      { en: 'ride', cn: '骑（马、自行车等）' },
      { en: 'right', cn: '对；正确的' },
      { en: 'river', cn: '河；江' },
      { en: 'room', cn: '房间' },
      { en: 'ruler', cn: '尺；直尺' },
      { en: 'run', cn: '跑；奔跑' },
      // S
      { en: 'sad', cn: '悲哀的；伤心的' },
      { en: 'Saturday', cn: '星期六' },
      { en: 'say', cn: '说；讲' },
      { en: 'school', cn: '学校' },
      { en: 'schoolbag', cn: '书包' },
      { en: 'science', cn: '科学' },
      { en: 'season', cn: '季；季节' },
      { en: 'second', cn: '第二' },
      { en: 'see', cn: '看见' },
      { en: 'September', cn: '九月' },
      { en: 'seven', cn: '七' },
      { en: 'seventeen', cn: '十七' },
      { en: 'seventh', cn: '第七' },
      { en: 'she', cn: '她' },
      { en: 'shirt', cn: '衬衫' },
      { en: 'shoe', cn: '鞋' },
      { en: 'short', cn: '短的；矮的' },
      { en: 'shorts', cn: '短裤' },
      { en: 'should', cn: '应该' },
      { en: 'sing', cn: '唱；唱歌' },
      { en: 'sister', cn: '姐；妹' },
      { en: 'sit', cn: '坐' },
      { en: 'six', cn: '六' },
      { en: 'sixteen', cn: '十六' },
      { en: 'sixth', cn: '第六' },
      { en: 'skirt', cn: '裙子' },
      { en: 'sleep', cn: '睡觉' },
      { en: 'small', cn: '小的' },
      { en: 'soccer', cn: '足球' },
      { en: 'sock', cn: '短袜' },
      { en: 'sofa', cn: '沙发' },
      { en: 'some', cn: '一些；某些' },
      { en: 'sometimes', cn: '有时；间或' },
      { en: 'son', cn: '儿子' },
      { en: 'sorry', cn: '对不起的；难过的' },
      { en: 'speak', cn: '说话；讲话' },
      { en: 'sport', cn: '体育运动' },
      { en: 'spring', cn: '春天；春季' },
      { en: 'stand', cn: '站；站立' },
      { en: 'start', cn: '开始' },
      { en: 'stop', cn: '停止；停下' },
      { en: 'story', cn: '故事' },
      { en: 'student', cn: '学生' },
      { en: 'study', cn: '学习；研究' },
      { en: 'subject', cn: '学科；科目' },
      { en: 'summer', cn: '夏天；夏季' },
      { en: 'Sunday', cn: '星期日' },
      { en: 'sunny', cn: '阳光充足的；晴朗的' },
      { en: 'sweater', cn: '毛衣' },
      { en: 'swim', cn: '游泳' },
      // T
      { en: 'table', cn: '桌子' },
      { en: 'take', cn: '拿；取；携带' },
      { en: 'talk', cn: '谈话；交谈' },
      { en: 'tall', cn: '高的' },
      { en: 'tea', cn: '茶' },
      { en: 'teacher', cn: '教师；老师' },
      { en: 'telephone', cn: '电话' },
      { en: 'television', cn: '电视机' },
      { en: 'tell', cn: '告诉' },
      { en: 'ten', cn: '十' },
      { en: 'tennis', cn: '网球' },
      { en: 'thank', cn: '感谢' },
      { en: 'thank you', cn: '谢谢你' },
      { en: 'that', cn: '那；那个' },
      { en: 'the', cn: '这；那' },
      { en: 'their', cn: '他们的' },
      { en: 'them', cn: '他们（宾格）' },
      { en: 'then', cn: '然后；那么' },
      { en: 'there', cn: '在那里' },
      { en: 'these', cn: '这些' },
      { en: 'they', cn: '他们' },
      { en: 'thin', cn: '瘦的；薄的' },
      { en: 'thing', cn: '东西；事情' },
      { en: 'think', cn: '认为；想' },
      { en: 'third', cn: '第三' },
      { en: 'thirteen', cn: '十三' },
      { en: 'thirty', cn: '三十' },
      { en: 'this', cn: '这；这个' },
      { en: 'those', cn: '那些' },
      { en: 'three', cn: '三' },
      { en: 'Thursday', cn: '星期四' },
      { en: 'time', cn: '时间' },
      { en: 'tired', cn: '疲劳的；累的' },
      { en: 'to', cn: '到；向' },
      { en: 'today', cn: '今天' },
      { en: 'together', cn: '一起；共同' },
      { en: 'tomato', cn: '西红柿；番茄' },
      { en: 'tomorrow', cn: '明天' },
      { en: 'too', cn: '也；太' },
      { en: 'toy', cn: '玩具' },
      { en: 'tree', cn: '树' },
      { en: 'T-shirt', cn: 'T恤衫' },
      { en: 'Tuesday', cn: '星期二' },
      { en: 'TV', cn: '电视；电视机' },
      { en: 'twelve', cn: '十二' },
      { en: 'twenty', cn: '二十' },
      { en: 'two', cn: '二' },
      // U
      { en: 'umbrella', cn: '伞' },
      { en: 'uncle', cn: '叔；伯；舅；姨父；姑父' },
      { en: 'under', cn: '在……下面' },
      { en: 'understand', cn: '理解；懂得' },
      { en: 'up', cn: '向上' },
      { en: 'us', cn: '我们（宾格）' },
      { en: 'use', cn: '使用；用' },
      { en: 'usually', cn: '通常；经常' },
      // V
      { en: 'very', cn: '很；非常' },
      { en: 'visit', cn: '参观；访问' },
      { en: 'volleyball', cn: '排球' },
      // W
      { en: 'wait', cn: '等；等待' },
      { en: 'walk', cn: '走；步行' },
      { en: 'wall', cn: '墙' },
      { en: 'want', cn: '想要；需要' },
      { en: 'warm', cn: '温暖的' },
      { en: 'watch', cn: '观看；注视' },
      { en: 'water', cn: '水' },
      { en: 'we', cn: '我们' },
      { en: 'wear', cn: '穿；戴' },
      { en: 'weather', cn: '天气' },
      { en: 'Wednesday', cn: '星期三' },
      { en: 'week', cn: '周；星期' },
      { en: 'weekend', cn: '周末' },
      { en: 'welcome', cn: '欢迎' },
      { en: 'well', cn: '好；健康' },
      { en: 'what', cn: '什么' },
      { en: 'when', cn: '什么时候；何时' },
      { en: 'where', cn: '在哪里' },
      { en: 'which', cn: '哪一个' },
      { en: 'white', cn: '白色（的）' },
      { en: 'who', cn: '谁' },
      { en: 'whose', cn: '谁的' },
      { en: 'why', cn: '为什么' },
      { en: 'window', cn: '窗户' },
      { en: 'winter', cn: '冬天；冬季' },
      { en: 'with', cn: '和；跟；用' },
      { en: 'woman', cn: '女人；妇女' },
      { en: 'word', cn: '单词；词' },
      { en: 'work', cn: '工作' },
      { en: 'write', cn: '写；书写' },
      // Y
      { en: 'year', cn: '年' },
      { en: 'yellow', cn: '黄色（的）' },
      { en: 'yes', cn: '是；是的' },
      { en: 'yesterday', cn: '昨天' },
      { en: 'you', cn: '你；你们' },
      { en: 'young', cn: '年轻的' },
      { en: 'your', cn: '你的；你们的' },
      // Z
      { en: 'zoo', cn: '动物园' },
      { en: 'nervous', cn: '紧张的' },
      { en: 'normal', cn: '正常的' },
      { en: 'notice', cn: '注意' },
      { en: 'number', cn: '数字' },
      { en: 'opinion', cn: '意见' },
      { en: 'opposite', cn: '相反的' },
      { en: 'ordinary', cn: '普通的' },
      { en: 'organize', cn: '组织' },
      { en: 'original', cn: '原始的' },
      { en: 'ourselves', cn: ' ourselves' },
      { en: 'outside', cn: '外面' },
      { en: 'perhaps', cn: '也许' },
      { en: 'personal', cn: '个人的' },
      { en: 'physical', cn: '身体的' },
      { en: 'picture', cn: '图片' },
      { en: 'pleasant', cn: '愉快的' },
      { en: 'popular', cn: '流行的' },
      { en: 'position', cn: '位置' },
      { en: 'possible', cn: '可能的' },
      { en: 'practice', cn: '练习' },
      { en: 'prepare', cn: '准备' },
      { en: 'present', cn: '礼物' },
      { en: 'problem', cn: '问题' },
      { en: 'produce', cn: '生产' },
      { en: 'promise', cn: '承诺' },
      { en: 'protect', cn: '保护' },
      { en: 'provide', cn: '提供' },
      { en: 'purpose', cn: '目的' },
      { en: 'quality', cn: '质量' },
      { en: 'question', cn: '问题' },
      { en: 'quickly', cn: '快速地' },
      { en: 'realize', cn: '意识到' },
      { en: 'reason', cn: '原因' },
      { en: 'receive', cn: '接收' },
      { en: 'recognize', cn: '认出' },
      { en: 'recommend', cn: '推荐' },
      { en: 'regular', cn: '规律的' },
      { en: 'remember', cn: '记得' },
      { en: 'respect', cn: '尊重' },
      { en: 'responsible', cn: '负责任的' },
      { en: 'result', cn: '结果' },
      { en: 'return', cn: '返回' },
      { en: 'science', cn: '科学' },
      { en: 'season', cn: '季节' },
      { en: 'second', cn: '第二' },
      { en: 'several', cn: '几个' },
      { en: 'similar', cn: '相似的' },
      { en: 'simple', cn: '简单的' },
      { en: 'situation', cn: '情况' },
      { en: 'society', cn: '社会' },
      { en: 'special', cn: '特别的' },
      { en: 'specific', cn: '具体的' },
      { en: 'speech', cn: '演讲' },
      { en: 'straight', cn: '直的' },
      { en: 'strange', cn: '奇怪的' },
      { en: 'student', cn: '学生' },
      { en: 'subject', cn: '科目' },
      { en: 'success', cn: '成功' },
      { en: 'suddenly', cn: '突然地' },
      { en: 'suggest', cn: '建议' },
      { en: 'support', cn: '支持' },
      { en: 'surprise', cn: '惊喜' },
      { en: 'surround', cn: '环绕' },
      { en: 'terrible', cn: '可怕的' },
      { en: 'therefore', cn: '因此' },
      { en: 'though', cn: '虽然' },
      { en: 'through', cn: '通过' },
      { en: 'together', cn: '一起' },
      { en: 'tomorrow', cn: '明天' },
      { en: 'tonight', cn: '今晚' },
      { en: 'toward', cn: '朝向' },
      { en: 'traffic', cn: '交通' },
      { en: 'trouble', cn: '麻烦' },
      { en: 'understand', cn: '理解' },
      { en: 'usually', cn: '通常' },
      { en: 'various', cn: '各种各样的' },
      { en: 'village', cn: '村庄' },
      { en: 'visitor', cn: '访客' },
      { en: 'weather', cn: '天气' },
      { en: 'welcome', cn: '欢迎' },
      { en: 'whether', cn: '是否' },
      { en: 'without', cn: '没有' },
      { en: 'wonder', cn: '想知道' },
      { en: 'yesterday', cn: '昨天' }
    ],
    semester2: [
      { en: 'festival', cn: '节日' },
      { en: 'geography', cn: '地理' },
      { en: 'humanity', cn: '人性' },
      { en: 'industry', cn: '工业' },
      { en: 'justice', cn: '正义' },
      { en: 'knowledge', cn: '知识' },
      { en: 'laboratory', cn: '实验室' },
      { en: 'management', cn: '管理' },
      { en: 'necessary', cn: '必要的' },
      { en: 'observation', cn: '观察' },
      { en: 'participate', cn: '参与' },
      { en: 'quality', cn: '质量' },
      { en: 'recommend', cn: '推荐' },
      { en: 'scientific', cn: '科学的' },
      { en: 'technology', cn: '技术' },
      { en: 'universe', cn: '宇宙' },
      { en: 'valuable', cn: '有价值的' },
      { en: 'wonderful', cn: '精彩的' },
      { en: 'youth', cn: '青春' },
      { en: 'zoology', cn: '动物学' },
      { en: 'ability', cn: '能力' },
      { en: 'benefit', cn: '好处' },
      { en: 'challenge', cn: '挑战' },
      { en: 'determine', cn: '决定' },
      { en: 'encourage', cn: '鼓励' },
      { en: 'familiar', cn: '熟悉的' },
      { en: 'gradually', cn: '逐渐地' },
      { en: 'horizon', cn: '地平线' },
      { en: 'influence', cn: '影响' },
      { en: 'journey', cn: '旅程' },
      { en: 'landscape', cn: '风景' },
      { en: 'method', cn: '方法' },
      { en: 'nutrition', cn: '营养' },
      { en: 'opportunity', cn: '机会' },
      { en: 'perspective', cn: '观点' },
      { en: 'quantity', cn: '数量' },
      { en: 'relationship', cn: '关系' },
      { en: 'solution', cn: '解决方案' },
      { en: 'tradition', cn: '传统' },
      { en: 'unique', cn: '独特的' },
      { en: 'volunteer', cn: '志愿者' },
      { en: 'wisdom', cn: '智慧' },
      { en: 'anxious', cn: '焦虑的' },
      { en: 'brilliant', cn: '辉煌的' },
      { en: 'concentrate', cn: '集中' },
      { en: 'disappoint', cn: '使失望' },
      { en: 'embarrass', cn: '使尴尬' },
      { en: 'fortunate', cn: '幸运的' },
      { en: 'grateful', cn: '感激的' },
      { en: 'hesitate', cn: '犹豫' },
      { en: 'incredible', cn: '难以置信的' },
      { en: 'jealous', cn: '嫉妒的' },
      { en: 'magnificent', cn: '壮丽的' },
      { en: 'numerous', cn: '众多的' },
      { en: 'overcome', cn: '克服' },
      { en: 'persuade', cn: '说服' },
      { en: 'remarkable', cn: '非凡的' },
      { en: 'sensitive', cn: '敏感的' },
      { en: 'tremendous', cn: '巨大的' },
      { en: 'ultimate', cn: '最终的' },
      { en: 'valuable', cn: '有价值的' },
      { en: 'worthwhile', cn: '值得的' }
    ]
  },
  grade8: {
    semester1: [
      { en: 'agriculture', cn: '农业' },
      { en: 'broadcast', cn: '广播' },
      { en: 'commerce', cn: '商业' },
      { en: 'diplomat', cn: '外交官' },
      { en: 'engineer', cn: '工程师' },
      { en: 'abroad', cn: '国外' },
      { en: 'accept', cn: '接受' },
      { en: 'accident', cn: '事故' },
      { en: 'active', cn: '活跃的' },
      { en: 'actually', cn: '实际上' },
      { en: 'advantage', cn: '优势' },
      { en: 'advertisement', cn: '广告' },
      { en: 'advice', cn: '建议' },
      { en: 'affect', cn: '影响' },
      { en: 'afraid', cn: '害怕的' },
      { en: 'against', cn: '反对' },
      { en: 'age', cn: '年龄' },
      { en: 'agree', cn: '同意' },
      { en: 'ahead', cn: '在前面' },
      { en: 'air', cn: '空气' },
      { en: 'allow', cn: '允许' },
      { en: 'almost', cn: '几乎' },
      { en: 'alone', cn: '独自' },
      { en: 'along', cn: '沿着' },
      { en: 'already', cn: '已经' },
      { en: 'also', cn: '也' },
      { en: 'although', cn: '虽然' },
      { en: 'always', cn: '总是' },
      { en: 'among', cn: '在...之中' },
      { en: 'amount', cn: '数量' }
    ],
    semester2: [
      { en: 'finance', cn: '金融' },
      { en: 'geology', cn: '地质学' },
      { en: 'heritage', cn: '遗产' },
      { en: 'industry', cn: '工业' },
      { en: 'journal', cn: '日志' }
    ]
  },
  grade9: {
    semester1: [
      { en: 'achievement', cn: '成就' },
      { en: 'breakthrough', cn: '突破' },
      { en: 'conservation', cn: '保护' },
      { en: 'development', cn: '发展' },
      { en: 'environment', cn: '环境' }
    ],
    semester2: [
      { en: 'foundation', cn: '基础' },
      { en: 'generation', cn: '世代' },
      { en: 'hypothesis', cn: '假设' },
      { en: 'innovation', cn: '创新' },
      { en: 'judgment', cn: '判断' }
    ]
  }
};